#include <cstdio>

void v0();
void v1();
void v2();
void v3();
void v4();
void v5();
int main(){
	freopen("mines.in", "r", stdin);
	freopen("mines.out", "w", stdout);
	int n, m;
	scanf("%d%d", &n, &m);
	if(n==3 && m==5)v0();
	if(n==25 && m==35)v1();
	if(n==60 && m==40)v2();
	if(n==20 && m==150)v3();
	if(n==222 && m==222)v4();
	if(n==4 && m==400)v5();
	return 0;
}

void v0() {
printf(".XXX.\n.XX..\nXX...\n");
}

void v1() {
printf("\
XX....X.XXX.XXX.XXX.X......X..XX.XX\n\
XX.X.X.X...XXX....X.XX..X...XXXXX..\n\
X..XXX.X.....X.XX.XXXX.X.X...XXX.XX\n\
XXXXX.......XX.XXX.XXX.X..X.X...XXX\n\
X...X.XX.X.X..XXXX..X...XXXXXX.XX..\n\
XXXX.X.X..X......X....X..X...XX..XX\n\
......X.X..XXXXX....XXX..X.XX...X.X\n\
.XXXX.X.XX...X...XX.X.XXXXXX...X.X.\n\
..X.....XX.XX...XX.X.X...XXXX.XX.X.\n\
X.X....X.X.....X...X.XXXX...X.XXX..\n\
.X.....X.XXXXX..X.XXXX....XX.XXXXX.\n\
XX.XX..X.X.X..XXXXXXXXX.XX...XX....\n\
XXXXX.X.X...X.X..XXXX.XX.X.X.XXX.XX\n\
XX.X...X..XXX.X.XX.XXX.XXXX.XX.....\n\
.XXXXXX.X.X.X..XXXXX.....XX.XXX...X\n\
X...X.....XXXXXX.XX...X.X.X..X.XX.X\n\
..XX.XXXX.....X...X.XXXX....XXXX.X.\n\
.X......X.X.X..XXX.X..XX.X.X..XXX..\n\
.XX.XX.X.X.XX..X.X...XX..XX.XX.XXX.\n\
..XX...XXX.X..XXX.XXXXX.X.XX.XX.XX.\n\
X.XX.XXXX....XXXX.X.X...XXX....XXXX\n\
XXX...X.XX..XX..X...XX..X.X...X.XXX\n\
.X..X...XXXX...X.X.X.XX.X..X..XXXX.\n\
XXX.X.XX....X.XX.X..X...XXXXXXXX..X\n\
.X...X.XXXXXXX.XX.XXXX.X..X...XXXXX\n\
");
}

void v2() {
printf("\
.XX...XX...X.X...X...XX.X.X.XXX.XX...X.X\n\
X.X.XXX....XX....X.XX..X..XXX.XXX..XXXXX\n\
.XXX...X.XXX..X.X.X.X..XXX.XXX.XXXXXXXXX\n\
XXXX.X..X..XX....XXXX..X.XXXX.XX.....XXX\n\
XXX.X...XXXXXXX.XXXXX...X..XX..XX..X.XX.\n\
...X.XXXXXX.XX.XX.XX..XXXX.XX......X.X..\n\
XX..X..XXXXX.XXX..XXXXX.X....X.X.X.X.X.X\n\
XXX...XX.XXXX.XXXXXXXXX.XXX..XX..X.XX.X.\n\
...X...XXXXX...XXXXX.XXX.X..X..XXX.XX...\n\
.XXX.XXXXX.XXXXX...XX.....X.XXXXXXX.....\n\
XXX...X..X...XXX.XX...X.X.XXX.X..XX..XX.\n\
X...XXX...XXXX.X.XXX...X.X..........X..X\n\
X.X.X..XX.XXX...XXX.X.X.....X.XX..X.X.X.\n\
X.XXXX.....XX.....X....XXXXX..XX.X.X....\n\
.XXXX..X..X.X..XXXXXXXX......XXXX...XXXX\n\
X.XX...X..X.XXXX......X.X.XXXXXXX..X.X..\n\
.XX.X.XXX.XXX...X.X..X.X.X..X...XXXXX.X.\n\
X.X.X...X..XX..XX.XXXX.XXXXX.XX....XXXXX\n\
.XXX..X.X.XXXX..XX...X..X..XX.XXXX..X.X.\n\
X....XX..X..XXXX..X.XXX.XX..X.XX..X..X..\n\
XXXX...X......XXX.X..XX...XX.XX..XX..X..\n\
.XX.X.....X.X..XX.....X..X..X.X.X.X.X.XX\n\
X.XXXXX..XX.XX...XXX..XX....X..X.X.XXX..\n\
X...XX..XXXXXX..XXXXXXX..X...XX.X.XXXXX.\n\
.X.XXX..XX.XX.XXXX.XXX..XX.X.XX.X.XX..XX\n\
.X...XX.XX..X.X..XX.XXX..X.XXXXXX.XX.XXX\n\
X....XX.XXX.X.X..XXXX.XX.X.....X.X.XX...\n\
...X.X..X....XXX..X.XX.....X......X.X.X.\n\
..XX.XXX.XXX.XXXX..XXXX...X..........XX.\n\
X..X..X..X.XX.X.XX..X.XX.XXX.XX..X.XXX.X\n\
X..XX...X...X...X.X.X.XXX.XX.X.XX.X.XX..\n\
.XX.XXXX.X...XX.XXX.X.X...X.X.XX..XX..X.\n\
X.X.....X...X.X....X.XX.X.XXXX..XXX..XX.\n\
.X.X.XXXX....XXX.....XXX....XX.X.X..X.X.\n\
X.XX.XX..X.XX..X.X......XX.XXX..X.XXX.X.\n\
XX..XX.....X..X.X...X.XX......XX.X...XXX\n\
XXXXXXX........X.XX..XXXXX.XX.XX..X....X\n\
X....XX.......X....XXXX...XX.X.X...X..XX\n\
....X.XXXX.X..X.X.XX.X.....XX..X.XXXX..X\n\
..XX...XXXX.XX.......XX....XX.....X.....\n\
.XX...X.XXX......X..XX..XXX..X.XX.XX...X\n\
.XXX...XX.XXX..X...XXX...XXX.XXX..XXX.X.\n\
XX...XX.........XXX.XX...X....XX.XXXX...\n\
XXXXX....X..X.X.XXX........X..XXX.X..X..\n\
.X.XX...X.XXXXX.....X.XX....XXX.XXXX....\n\
XX.X....X.X.X....X.X.XXX.XX.XXX.X.X.....\n\
.XX..X....XX..XXXX.XX.XXX.X..XX..X..X...\n\
...XXXX.XX.X.XX.....XX..XX.XX..XXXXX....\n\
X.X.XXXXX.XX..X.X..XXX.XXX..XX...X......\n\
.X.X....X.X..X...XX..XXXXX...XX...X.XX..\n\
XXXXX..XX..X.X.XX.X.XX.XX..X.X....X.X.X.\n\
XXX...X.XX.....X.X..X...X.X..XXX...X.XX.\n\
XXX..XX.XXXX..X.X.XXX.XX.X.........X...X\n\
XX....XXXXXX..X...X.XXX.X.X.X.XXX.X..X..\n\
XXXXX..X....XX..X..XX...X.X....X...XX...\n\
XX.XXXXXXX..X.X......XX..X.XX.XX.XX..X..\n\
.XXX.X.X.X..X.X..X..XXXX.XX.X.XXXX.XX.X.\n\
.X..X..X.X..X.X...X.X.X.X..XXX.X.XXXX..X\n\
XXXX..X.X..XX...XXXXXX..X.X.X..X.XX..X..\n\
.X...XXXX.XX.XX...X.XX.XXX.X.XXXX..X.X.X\n\
");
}

void v3() {
printf("\
.X.XXXX..XX.X.XXXXXXX...X....X..XX..XX....XXX....XX...XX...XX.XXXX......X.X..X..X....X...X.X.XXXX..XXXXX..X.XX...XX..XXX.X.X..X.X.X.XXXXXXX.XX...X..X.\n\
X.X..X.XX...X.X...XXX...X...XXX.X.XX.XXX.X.XXX..X.X.X.XX.XX..XX.XX.XXX.X...XXXXX...X.XX.XX..X.XX.XXXX..X....X.XX.XXX.XX.X.XX.XX....XX.X...XX..X...X...\n\
.X.XX.X..XXX.X.X.X.X.X.X....XXXX...X...XX.X..X.........X.X..XXX...XXXX.X...XXXX......X...XXX...X.X...XX.X..X.X.XX.X..XX.X....XXXX.XX.XX.XX.X...X..XXX.\n\
XX..X.XXXXXXXX.....X.X.XX..XXXXX...XXX...XXXXX....X.XX.X..XXX..X..X..X.XXX.XX...XXX...X.XX.X.XX.XX...X...X.X..XXXXXXX..X.X....XX.XX.X.X.X...XXXXX..X.X\n\
..X...XXXXXXX.XXX....XXXX.XXX.......X..X...X....X.XXX.XX.X..X..XX.XX..X..X.XXXXX.X..X.X.XX...X.....X.XX.X.XXX....X.XX...XX.XX.X..X..X.X.X...XX.XXXXX..\n\
.XX.XX..XX.XXX..XXX..X.X......X.XX..XXX..X.X.XXX.XX.X..X.X.X..XXXXXXXXX..XX..XXXX.XX.X.X.XX.X.X..X..XXX.X...XX..X.XXX.X..XXXX....X..X.XXX...XXX.XX.XX.\n\
.X.XX..X..X..X..X..X.X..XXX.....X.XXXX.X..X.X..X..XXXX............X.....X.X...X..X.X.X.XX..X..X.X.X.X..X.XX..XXX.X.XX......XXXX...XXX.....X....XX..XX.\n\
.X...X.X.X....XXXX.XXX..X.....XX.XX.XX.X.XXX.XXXXXXXX.XXX..X.......X.X......X...X.XXXX.....X..X.....X.X..XX....X..XXXX..X.X...X.....X......XXX.X.....X\n\
.X.XX.X.XX..X...X...X.X..X.XXXX.XXXXX.XX.X.XX.X.XX....XXXX.XX....X..XX.XX.XXX...X..X.XX..XX.XX....XXX..X.XX.XX.X.X.X.....XX..XX..XX..XXX.X.XX..XXX..XX\n\
XX.X.XXXX....XX.XX.....XX.X...XXX..X.XX.XXXXXX....XXXXXX.XXXX.XXXXXXX...XX....X....XX...X..XXX.XX..X..X.......XXXX....XXXXX...XX...X.XXX...XX..X....X.\n\
XX.X.X.XX..XX.XXXX..XXX.XXX.....X.X..XXX.XXXXX.X.X.X..XXX.XXX.X.XX.X..X.XXXX.XX.XX.XXX.XX.XX...X.X..XX...X.X....X...X.........XX.X.X.XX..X.X.XXX.X.X.X\n\
.XX.X..X..XX.XX...XXX.....X.......X...XXXXXXX.XXX...X.XXXX.X.X.....X.X.X..X.XX.....X.......XXXX..XXXXX..XXXXX.X.XX.XX....XX.X.XX.X....XXXX..XX....X...\n\
.XXXX....X.X..X....X...X..XXX.XXXXXX.X..X..XX.X.XX....X..X..XX.X.X.XX.X..X.XXX....XXX.X.XX.XXXXX...X.XX..XX.XXX..XXX.XX..XXXX.XXX.XX.X.X..X.X......X..\n\
X.X..X.XXX..X..X..XX.X.....X...X..X..XXXX.X.XX...X.X....XXX..XXX.X..XX.X...X.X......XX....XX..X.XX.XXXXX.X...XXX...XXX..X.XX.XXX.X.XX.XXX..X...X.X.X..\n\
.X.XXX..XX..XX....XX.X.XX..XX.X...XX....X..XX..XXX..XX.X....XX...X.XX...XXX......X..XX.X.X.X.X..X..XXX..X.X.XX.XXXXXX.XXXXX.X.XXX..XX..........XXX..XX\n\
XX..XXX..XXX..X...X.X....XXXXX..X..XX.....XXX..XXXXX..X...X...X....XXX.XXX..X...XX.XXXXX..XXX..X.XXX.X.....X....X.X..XXX.X...X....XX.X.XXXXX...X.XX.X.\n\
..XX..XXX.XXXX..X..XX.XXX.XXXX.X.XXX...X.X..X...XX..XX.X..X..XX.XX..X...X....XXX..X.XXX.XX..XXXX...X....X.X..XX..XX...XXX.XXX..XXXX..X.XXX....XXX...XX\n\
X....X.X.XXXX.XXXX.XX.X.X..X.X..XXXX..X.XXX..X..X.XX..XXX....XX.XX.XX.XXXX.XXXX..XX.XXXXXXXXX...XX.X.XXX.XXXXXX..XXX.XX.X...XXX.XX...X.X.XX..X....XXX.\n\
.X.XXXX.XX.XXXX.X.XXX.XXXX.....X.XX..XX.XXXX.X.XX.XXX..XX.XXX.X..X...XXXXX.XX.XXX.X..XX.X.X.X.X.XX.X.XXX...XX.X.XXXXX..X.XX.XX.X..XX..XX..XX.....XXXX.\n\
X..XXX.XXX.XXXXX.XX.X.XXX..XX.XXXX..XXXXXX....X..XXX.X.XX.XXX..X....X....XXX.......X.X.X...XX.XXX..XXX....XXXXXX..XXX....X..XXX.X.X..XX...XX.XX.XX...X\n\
");
}

void v4() {
printf("\
...XX..........XXXXX.XX.X.X...X.X....X..X...X.X.XXX.X.XX.X.X..XXX.XXXXX..XX....X.XXXXXXX..XX..XXXXX.XXXXXXXX.XXX.XX.X.X.X.X..XX.X.X.....XXXXXX.XX.X...X..X....X..XXXXX..X.X..XX..XXX..XXX.X..X.XXXXXX.XXX..XX.X.X.XX..X.XX..XX\n\
X.XX.XXXXX.X.....XX.XX.X..XXXX.X..XX.X.X.........X.X.....X.X.XXX.XXX...XXX.......X....XXXXXXX.XXXX.X...X.....X.X.....X.X.....X..X..XXX..XXXXXX....X.XXX.XX..X..X.XXXX..X.X.XX.XX.XX.X.....X..XXX.X.X.XX.XX..X.XX.X.....XXX.X.X\n\
XXX..X.....X.XX.XX.XXX.XX.XXX.X.XXX..XXX..XX.X.X.X.X..X..X.XXXX.XX.XXX.X..X.X...X.XX.......XX.....XXXXXX.X...XXXXXX..XX....XXX..XX.X.XXX.X.X.XXXX..XX...X..X..XX..X.X..XXXXXX....X....XX...X.XXXX....XX.X.XXXXX..XXXXX.X.X.X.X\n\
X...XX.X..X....X...XXXXXX....X.XXXX.....XX......X.X....X.X.XXXX...XXXXX.X...XX..X.....X.X.XX.X....X.X....XXXXX.....X.X.X.XXXXX...XXX..XXX...XXXXXX.X....X..XX...XX...XXX..X.XXX.X.X.X..XX.XX.X..XX..X.XX..XXXX...XX..XX...X...\n\
X.XXX.XX..XXXXX.XXX.XXXX.X...XXXXXXXXX....XX.XXXXX.XXX..X.X.XXXXXXX.....X...X.X..X.XX..XXXX..X..X...XXXXXX..XXXX..XX....X.XXXXX..X.X..XX.X.XX..X...XXX.X.X.XXX..XXX...XXXXX........X.XXXXX..X...X.XX..XXX.XX..X.XX.XXXXXXX...X\n\
..XX.X...X..X...XX.XX.X..XX..XX..XXXX..XX.X.XX.....XX..X.X.......X..X...XX..XX.X...XXXX.XXXX..X..XX....XX.X.XXX.XXX.X..XXX....X..XX.X.XXXX..XX..XX.XXXXXXX.....XXXXX.X.X...X.XXX..X.XXXXXX..X.XXX...XXXXXXXX.X.XXXX.XXXX.XXXXX\n\
XX..X...XX.........XX.X.X.XX.XXXX..XXXXX...XXXX.XXXX..X.XX.X......X.XXX..XX.XXXX....XXXX..XX.X.X..X.XX.X.XXXX....XXXX.XX...XXXX..X....XXXXX..X.X...XXX.X..X.X.XX.X..XX..XXX.XXXXX.XXXX..X.XXX..XX.X.X...XX..X..X.XX...XX.X.XX.\n\
XXX.X.XXX.X...XX...X...XX...X.X..XX.X...X.XX..X.X.X..X.X...X.....X..XXXXXX...X...X.XXX...XX...X.XXX.XX...XX..X..XX.XXXXXXXX.X..X..XXX.....X...X..........XX.X...X..XX....XX....XX.XX..X.XX.XXXXXXXXX..XX..XXX....X.XXXX..XXXX.\n\
.X..X.XX.X..X..XXX....XX..XXXX.XXXXXX......X.XXXX.X..XXXXX..X.X.XX.X.....X.X..X.XX.XX.X...XX...XX...XXX.XX.X....XX.XX.X..X......X.X.X.XX.X.XX.....XXX.XX.XXX......X.XX..X..X.XXXX.XX..XXXXX..XX..X......X.X...XXX..XXXX..X....\n\
...X.X..XXXXX.XXX.X...X.XXX.X.XXX..XXX...X...X..X..X...X.XX.X...XXX.X.XXXXX...X...X.XXX...X......X..XX.XXXXXXX..X..XX...X..X.......XX...XXX.XX.....XXX.XX..X.X.XXX..XX..X.X....XXXXXXXXX..X.XX..X.X.XXXXX..XX.X..XX.X.....XXX.\n\
.X.X..X.XX...X...XXXX.X..XXX..XXX..XXXX.X.X.XX..XX.X.XX...XXXXX...X.XXX.X.....XX.XXX..X.X.X...X...XXX.XXXX.X.X.X.XX.X..XX.XX..XX.XX..X.X..XXXXX.X......XX..XX.XX.XXXXX..X.XXX.XX....X...XXX.X.XX..XXX......XX.....X.X.XX....X.\n\
XXX.X.XXXXX..XX.XX.XX.X.X..XXX....XXXXXX.XX.X..X.XXX.X...X.XX..X..XX.......XX.XX..XX.XX.X.XXXXXXXX.XXX.XXXX..XXXX.XX..XXX.XXX...X.X..XXX.X.XXXX.X.X..XX...X...XX.XXX.....XXX.X....XXXXX.X.XX.XXX.XX.X..XXX.X..X..X...X.X....X.\n\
X.X..XX.X...X....X.XX.X.X.X..XXX.....X..X.X.X..X.XX.X..XXX.X.X..X....X..X..XXX.XXXXXX..XXXX.XX..X.X.X.XXX.X...XX..X.XX.X.X.X..XXX....XXX.XXX..X.X.X.X...XXX.....X.X...XX.X....X..XXX.XX.X.XXXXXX.X.X.XXXXXXXX.XXX.XX.XXXX..X.X\n\
X.X.X.XXXX...X.X.XX.XX...XX.X...X.XX.XXXX..X.X.X.X..XXXX.X.XX...XXX...XXX.X.XXXXXXX..X.XXXXX...XXX.XXXX.XXXXXX..XXX.....XXXX.X.X.XXX.X.XX.XXXXX.X.....XX..X..X..XX...X....XX..X.XX.XXX...X..X....X..XXXXXX........XXX.X...X.XX\n\
XX..X.XXXX.XX..XXX.XX..X...X.XX.XXX..X.XX...X...X...X.XX.X.X.XXXXXX.XX..X.X.XX...X.X..X..X....X.X...X...XXX.XX.XXX..X...X...XXX.X...XXXXX..X...X.XXX..X..X...XX...XXXXX..XXX.X.X.X......XX...XX.XXXX.XXX.X...X.XX.XX.XXX.XX..X\n\
X..XXX..XXXX.X.X.X.XX.X..X.XXXX...XXXX..X.X.X.XX.X......X.X..X.X.XXX.X.XX.X..X.XX..X..XX.X.XX.X..X..X.X...XXXX.XXXXXX.XXX....XX.X.XX.......X...X...XX..X.X.XXXXXXXX.XXX..X.....X.X...X...XXX......X.X....X....XXX.XX.X..X.XX..\n\
X.X...XX..X.X..X.X....X.X.X.XXXXXXX.X.X.X.XX.XX..X...X.X.X..X...XX.XX.........X...X..XX..X..XXXXXXXX.X.......X..XX..XXXXXXXX.XX.....X.X...XXXXXX.XX..XXXX.XXX.X.XXX.X.X.X..XX.X.........X.X.X.XXXX.XX.....XXXXX...XXXXXXX.XXXX\n\
X.X.XX.....X.X.X.X.........X..XX......X.XX...XX..XXXXX...XXX..X...X.XXXX....XXXXX...X....XX..X.X..XX.XX.XXXX..X..X....X...XX.X.X.......XX.XX.X..XX.XXX..X.XXXX.XX.XXX..XX..XX.....XXXX.XX..XXXXXXX..X..XXX...X..X..X.X...X.XXX\n\
.X..XX..XXXXXXX..X.X...XX....XX...X.X......X..X.X.X.X.X.XX...X..XX.XXXXX.XX..X..XX.X.XX.X...XX.X.X..X.XX...X..X..X..X.XX..XX.XX.X.XX.XX.X....XX...X..XX.XX..XXXX......XXX.XXX.X..XX....XX.X.XX.X.XX...X.X.X..X.X.X...X..XX.X.X\n\
X..X.X..X....X...X.....X...XXXXXX.X.XXXXXXXX...X..XXXXXX.X.X...X.......XXXX.XXXX.XXXXXXXXX.XXX.XX.XX.X..XXX.X..X..X...X.XX.X.X...X.X.X.XXX.XXXX.....X.XXX.X...XXXX.X...XXX.XXXX..X.X....X.X.X.....X.X.X......XXX.X.X.XX..X.XXX\n\
..XX.XXXXX.X..X....X...X.X.X.X..X.......XXX.XX..X..XX.....X..X.X...X.X..X.XXXXX.X...XX..X.X...X.XXXXXXX..X..X.X.X.X.XXX..X.X..X..X..XXXXXX.X..X.X.XX....X....X.X.X..X.X...XX.XXX....X.X.X.X.XXX...X.X.X..X.X.X.X...XXXXXXX....\n\
..X.X.XX..XXXX......XXX....XX...X...XX.XXX...XXXX...X....XXX...X..XX.XX..XX.XXXXX.......X.X.XX.XX.XX..X.X.X...X..X..X...X.XX......XX.XXXXXXXXX.X.XXX..X..XXXXXX.XX.X..XXX.....XXX.X.X..XXX....XXX.X...X.XXX.XXX...........X.XX\n\
XXX.XX.X.X.X.X...XX.XXXX.X.XX.X..XXXX..X.X...X..X.X..X..XX.XXX..X......X.XXXXXXX..X..XXXXX.X.X..XX.XXX.XXXX...XXX.XX....XX..XXX...X....X.X.XX..XX.X..X.XX..X..X.XX....X....X....XX.XX.XX.X.X.....XXX..X.XXX.XXX...X.XX.X..XXX.\n\
.X.XXXX..X.X..XXXXXX..X..X..X.XX.XX..X....X.X...X....XXXXXX.X.XXX...XX..XXX.X..XXXX.XX..XXX.XX.XXX.X.X..XX.XX...X...X.XXX.X....XXXXXX.....XXXX.X.X.X.XX...XX..X.X.X...XXX.X.X.X.XXX..XXX.X.....XX.X.X.......XX..XXXXX..X......\n\
X.X.XX......XXX..XX...X.XX.X.XX.X....XX..XXX.X.X..XXX.XX...XX.X..X..X.XXX..X.X....XX..X.....X.X.....XX.X.XX.X.XXX..X...X.X..XXX...XXXX....XX.XX.X...XXX.X...X.X.XXX..XXX.X.....X...X..X......XXXX.XXXXX..XXX.X..X.X..XX...XX.X\n\
X.....XX.XX..XXXXXX..X.XX...XX.XXXXXXX...X....XXXXX..XXXX.X.X.XXX...XXXXXX..X.X..X..XX.XXX...X.X.....XX..X.XX.X.XX.......XX.X....X.XXXX.XXXX.....XX.X.XX..X.X..XXXX..X.....X.X.XX..XXX..X.X..XXXXX..XXX.X.X..X.X..X..XXXX...XX\n\
XX.XXX.XXX.XX.X.X.XXX.X..X.XX.XXXX.XXXX...XX.XXXXX.XXXX..X.X.X.X.XX..X.XXX.X..X.XXXXXX.X......XXX.X.X.X..X.X..X.X.X.XXX.....X..XXXX..X.XXXXXX.XX.........XX..XX.X.X....XXX.XXXXX.XXX..XXXX.XXX.X.....XX.X.XX.XXX.X.X..XXX.X.XX\n\
X.X.XXX...X.X.X.XXXX.XXX.XX...X.XX.X.X.X..X..X.X.X....XX.X.XX......XXXX.X..XXX.X.......XXXXX.XX.X.X.XXXXXX.X...X..XXXX..X.X....XX.XXXXX.XX.X..XXXX.XXXX.X.XX......XXX..X..XXX..XX.XX....XX.X.XXX...X..XX.X.....X.XXXXX.X...XXX\n\
X.X..X.XXX...XX..XXX.X.XXX.X.XXXX.XX.XX.X..X...XXXX.X.X....XX..X..XX..XX...XX.XXX...XX..XX.....XXX..XX..XX.....XXXX...X..X...XX.XX.XXX......X..XXX..XXX.XXX..X...X..XX.X....XX.XX.XX.X..X.X.XXXX.....X....XX....X..X..XX..X..X\n\
X.X..X.XXXX.XX.XX.X.X.X..XXXXX.XX..X.XX....XX...XX.X.X.X.X....X.XXX.XX.XX.....X.....X...XX...X.XXX..XXX..X.X.XX......X..XX.XX...X.XXX.X.X.XXX.XXXXXX.XXX..X.XX..X.X.X.X..XX.X.X.XXXXX.XXX.....X......X....X..XXXX..XX.X..X.XX.\n\
X.XXX...X...X.XX..X.X...XX......X..X..XXXX.XX..XX...X........X..XX....X.XXXX..XXX.XX..XX.X..XXX...XX.X....XXX.XXX..X.XXX.X..XX....X.X.X....X.X..XXX..XX.XX...XXX...X.......X...XX.....XXXX..X...X..X.X..X...XXXX.XX.XX..X.X.XX\n\
XX......X..X...X.X.XXX.X..X..X..X..X.X.X....X.XXX....X.X.X..XX.X.XX.X.XXXX..X.XX.XXX.....X.XX...XX.X.X.XX.XXX.X..X.X....XX.X...XX.XXXX.X.X.XXXX.XX....XXXXXX..XX..XX....X...XX..XXXX..X.XX..X..X...XX.X..XX....X.X.X....X...X.\n\
..XX.......X.XXX.X.XX.XXXX..X..X.XXXXX...XXX...X.X..X.X....X.XX.X.X......X.X....X.X..X.XX.X.XX.X.X.XX..X.X.XX.X...XXX.X..XXXXX..X.....XXX..XX.XX.XX.XX.X...X.X..X..X..XX..XXXX.X..X.X.X.X.X.X..X....X..X..X.XX.XX.XX...X.XX.XX\n\
.X.X...X.X.XXX.XX...XX..X.X.....X..X....X..XX...X.XXXX..XXX.X.X..XX..X....XXXX...XXXXXX.X.XX.X..XXXXX.XXX.XXXXX..XX.XX.XXX.XXX..X..XX.XXX.X.X....X.X.X...XXX..X...X.X.X.X.XXX..X..XX.....X..XX.X.X.X.X..XX..X.X...X.XXX.XX.X..\n\
..X..X..XXXXX.X..X.XXXX...XXX..X..X..XXX.XX.XXXX.X.XXX.X......XXX..XXXX.X.XXX..X.X.X....XX..X...X..X.X......X...XX...XX....XX...X.....XXX.XX.XXX..XXXX......XXX.XX.X.XXXXX.X..X...XX..X..XXXXXX...X..X.X....X..X...X.XX.XX....\n\
XX.X.XX.X.XXXX.X.XXX..X.....X..X.X.XXX.X...XX...XXXXXXX.X....X....XX....X.X..XX..XXXXXX..XXXX..X.XXXXX...XX..XXXXX....X.X..X.XX...X...X.X.XX..X..XX....XXXX.......XX.X..XXX..X.XXXXX.X.X....X....X..XX.X.XXXX..X..XX..XXX...XX\n\
.X.X.XX..XX....X.XXX..X...XX.X.XXX.X.X.X.XX...XXXX..X..X...X...X...XXX..X.........XXXXXXX..X.XX.XX.X..XX....X.X...X..X..XXXXX.XXXXX..XXX..X..X..X...X..XXXX.X..XX.X.X....XXX....XXX.X.X.XX..X..X.X.X.X..XX.X.X..XXX.XX.X...XX.\n\
X.XX..XX...X..X..XXX...XXXX...XX.XX.XXXX.XX..XX.X......XXXX..XX.XXXXXX.XX.X...X.XXX......XXX..X...XX..X...XX...X..X.XX.X.XXX...XX...X.XX.....XX..XXXX.X.X....XXX.XXX.....XX..XXXX..XXXXXX..X.XXX..XX..X...X..XX..XX.X.XXXX.X.X\n\
....X.XX..X.X..X..X..XX..XXX.X.XXX.X...X..XX..XXX.X..XXXXX.XXXX.X.XXX.X.X.XXX.X.X.X..XXXX.X..XXXX.X.XXXX.XX..XXX.XXXX.XX.X...XXX.X..X......X.X..X.XX..XXX.XX.X......XXXX.......XXXX..X..X..X.X.X..XX...XX..XXXX.XXXX....X.XXXX\n\
XX.XXXXX..X......X.X.XX..XX.XX.X..X.X.X.X.X.XX...XXXXXXXX.XX.X.XX.XXXXXXX.XXXX..XXX..XX..XX.X...X.XX........XX...X...XX...XX.XXX...XXXXX.X.XX.XXXXX.XXXXX......XX..X.X...X.XX....XXXXX......XX...X..X..XX.XXXX..X.XX..X.......\n\
..X..XXXX.XXXXX..X.X.XXX.XX..XXX....X.X.XXX.X..XXXX.X..X.X...XX.XXXXX.XXXXX.XXX..X.XX..XXXX..X.X..XXX..X.XXX....X....XXX...X..X..X.......XXX.X.XXXX.XX.XXXX.X..X.XX.X.XXX.XX.XX....X..XXXX.X..X.XXX.XXX..XXXXXXXXX.X....X.....\n\
.X.X..X..XX..X......XXXXXX..XXXXX........XX....X...XX..X..X..X....X.....X.XX..X..X..X....X.X.X.XX..XXX..X...XX.X.X...XXXXX.XXX..XXX.XXX.XXX.X.XXXXX....X..XXXXX..X.XX..XX.XX.XXX.XXX.XXXX.X..XX.....XX....X.XX.XXXXX..XXXXX..X\n\
XXXX.XXX.XXXX.X.X...XX.X.X......X.X..XX.XX.X.X..XXXX.X.XX....XXX.X.XXXX.XXX...X.....X...XX.XXXX....XXXX.XXXXXX..X.XXXX..XX.X..XX..XXX.X....X.XXX....X..X.XX.XXXXX..XXXX.XXX..X.X...XX.XX.XXXXXX...XX..X.X...XXX.XXX..XXX.XX..X\n\
X..XXXX..XXX.XX..X.XXX..X...XX....X.XX.X...XX.X.X..X.X...X.XXX......X...XXXXXXX..X...X.X..X.XXXX.X.XXXX.X.X....X.XX.X.X.XX..XXX..X.X...X.X..X...X...X....XXX.X..X..XXXX.XXX...XXX.X.X.XX......XXXX...XX.XXXX..X...XXX.X.X.....\n\
.....X..XX.XXXX..X...........X.X...X..X..XXX.X.XX.XX.XXXXXX...XX.XXXXXX.XX.XXXXXXXXX.X.X.X.XX.XXX..XXX..X.XXX....XX.XXX..XXXX.....XXXX..XX...X..XXXXXXX.......X..XXXX.XXXXXXX.........X.XXXX...X.X.XXX.X.....X..X...XXXX.X...X\n\
.X.XXX..XXX..X.XX....X...XX.X...XXX...XXXXX.XXX.X.X..X....X.XXXX...X.X.XXXXX..X...X.XX.XX....XXXXX.XX.XXX..X...X.X..XXX.X..X.XXX.X...XXXX.XXX.X.X..XXX...X.XXX.XXXX.X...X...X...X.XXX..X..XXXXX.....X.XXX....XXX.X......X.....\n\
XX.XXX..X...X..X.X.X.X.XXXX.....X.XXXXX.XXXXXX.....X.XX.XXXXXX.X.....XX..X.XXX.X...XX.XXXXX.X....XX.X.X.......X.X.XXXX.X.XX.XX.X..XX......XX.XXX.X...XX.X.XXX..X.......X.XX.X.XXX...X.X.XXXX.X...X...X..X..X.XX.........X.XXXX\n\
..X..X.X.XXXXXX....X....X...XXX....X.XX...XX..X...XXX....X...XXX..XXX.XX...X.X.X.....XX.XX....XX...XXXXX.XX.X....X.XXX....XXX..XXX..XXXX.XX..X..XX.XX.XXXX..X..XX.X.X..X.X.XXXXXX.XX.XXX...X..XX...XX.X..XXX..X..XXX.X.X.X....\n\
.X...XXXXX.....X....XXX.X.XXX.XX.XXX..XXX.X.X...XXX.X....X....XX.XX.X..XX.XXX..X..XX.XXX........XX.......X..XXXX...X.XXX.XX.XXXXXXX..XX.X..XX.X..XXX..XX..X......X..X..XX.X.XX..X..XX.X.XXXX...XX.X..XX..XX..X.X..XXXXX.X..X.X\n\
.X.X....XX......X.XX...XXXX...XXXX.XXX..X.XXXX.XX.XXXXX.XXX..X.X.X....X.X.XX...X.X.X.X..XX.X....XX..XX.X.XXXX....XX.X..XX.XX.XXXXX.......XXX..XXXX.X...X..X..X..XXXXXX.X.X..XX...X...XXX.XXX.X..XXXXXX.....X..X.XX.XXX..XXXX.X\n\
...XXX..X.X.X.XX....X..X.XXX.X.XX..X..X.X..X......X..X.X...X...X..XX..X....X...XXX.XX..XXX.X..XX.X.XX.XXXX.XX.XX....XXXXXXX..XX...X.XX.XXX.XXX.X.X..X.X.XXX.X..XX.XX.X...XXXXX...X.X.XX..XX.....XX..XX.XX.X.XXXXX.XXXX.XX.XXXX\n\
XXXXXXX.....X...XX.XX.XX..XXX...XX...X..XX..X.X.XX.X..X...X.XX....X.X.XXX.XX..XX..X......X..X.XXX.XX....X...X.X..X.XXXXX.X..XX.X..XXXXX..X.X.X.X...XXX...X..X..X....X....X...XX..X......XX.X.X..X...X..X..X.XX.X.XX.X...XX....\n\
XX.X..XXXX..X..X.X...X..X.XXXX...XX.XX.X..X.X.XX.X...X.X..X..X....XX....XXXXXXX.XX..X..X...XX.X......XXXXXX.X.X..X....X..X...XX...XX..XXX..X.X.X.XXXXX..X.XX.XXXXX..X....XX.XXX...XX.XX.X...X.XX.X....X.XXX.XX.X..X...X.X....X\n\
...XX..X.XX..XXX..XX.X..X.X.X....X..X.XX..XXXXX.X.X....XXXX..X....X......XX.XXX..XX.XX......X.X..X...X.......X..X.XX.XX..XX......XXX.X.X....X..XXX.X.XX.X..XX..X..XXX.XX.XX....XX.XXX.X.X....X...XXXXX.....XXXXXX..X.XX..XXXX.\n\
.X....X....X..X.XX.X.XXXXXXX...XXX.XX.XXXX..XX.X....XX.X....XXX.XXXXXXXX..X.X.XXXX.X..X.XX.XXXX..XX.X.XX..XXXX...X..XX.X.X.XX..XXX....XX....X.....X.X.X.XX..X.XXX...X.XXX..X.XX....XXXXXXX....XX.XX....X..X.X.X..X.XX......X.X\n\
.XXXX..X.X.XX.XX...X.XX.X.XX...X...X.X.......XX..X...X.XX.X.XX.X..XX..XXXXX.XX.X.X.XXX.X.XX.X.X.XXXX.X.XX.XX.XX...XXX..X....X...X........XXX...XXXXX.XX.X.X.X..XXX.X....XX...X.XX.XXX...X.X.....X.X..X..X.X...XXX.XXXX.XXX.X..\n\
X.X....XX...XX.XX.XXX.X.....X..X..XXX...X.X.XXX.X.XX.X.XXX.XX..XXXXXX..X.......X.X.XXX.X....XXX.XXXX.XXXXXX...XX...X..XXXX....X.X..XXXXXX..X..X.X..XXX.XXX.XX.X..X..XXX...X.XX...X..XXXX...XXXXXXX..X.XX.X.X...XX.XX.....XXX..\n\
X.X.XX...X.XX..XX.X.XXXXX..XXXXXX.XXX....X.X.X..XXXX.XX..XXXX..XX.XX.X.X..X...X.......XXX.XXX.X.XX...X.X....X.....X.XX.X.....XXXX..XX.X.XX..X..XX.XX.XX...XX..XX..XX..X.X..X..XX..X..XX.X..XXX...X..X.X.XXXX...XX.X.XX.XX..XX.\n\
XXXX......X..XXX...X.X.XX....X...XXXX...X.X.X.XX..XXXXXXX...XXX.XX..XXXXXXXXX.X.XX..XX..X.X..X.X.X.XX.X...X...XX..XXX.XX..X......XX.X...XX.X.X.......X..X....XX...XX.XXXX.X..X.XXX.XXX.XXX...X..XXX..X.XX...X..X.XXXX.X.X..XX.\n\
XX..XXXXX....XXX.X..X.X....X....X.X.....X.XXX..XXX..X.X..X.X.....X..XX...XX.XXXXXXX.X..XXX.X.X.XX.....X..XXX...XXX.XXXXXXXXX..X..XXXXXXXX......XXX.XXXXX.....X.X.X..XXXXX...XXXX......X....X..X.XX.XXXXXXX...XXX.XX......XX.X.\n\
XX...XX....XXXX..XX.X...X.XXX.XX...XXX..X....XXX.XXXX.....X.XX.XXX.X.X.XX..X..XX.X.X..X..XX.X.....XX.XX.XX.X..X.XXX.XX.X..XX..XXXXX.X.XXXX..XXX.XXX.X.XXXXXXXXXX..XX.X......XXXXXX..XX.X.XX.X.....X..X...X..X.X.XXX......XX.XX\n\
..X.XX.X...X..X...X.....XX.X.X.XXXXXXXXX......XX.X.XXX.X..XX.X.X..XXX..XXXXXX...XXX...XXX..X.X..XXX.X......XXXX.....XX..X.X.X......XX.XXX..X....XX.....X..X.XXXXX.XXX....X.X.XX...X..X.X..XX..XX...XXXX.X..XX.X.XXXXX.X.XX...X\n\
X.X.XX.X...XXXXX.XXXXX.....XXXXX....XX.......X.XX..X.X...XX.XX.....X.XXX..X..XXX...XX.X.X.XXXX...XXXXXX.XX.X..X.XX.XX.X..XXXXXX...X.XX.X.XXXXX.X.X.X..XX..X.....XX..XX.XX.XX.XXXX..X.X.X..X.XXXXX....XXX...X...XX..X.X..X.XXXX\n\
.XX.XXXX..X..X..X.XX.X.X.X..XXX.X...XXX.XXX......X..XXXX...X.X...XXX..XX.X.X..XX.....X...XXXX.X.X.XX..XXXX..X...XX..XX.X.X.X...XX.........X....X.XX.X....X...X...XX.....XX.XX......X.X...X..XXXX.X....X...XXXXXXX..X..XX.XX.XX\n\
..XXX..XXXXXX.XX....XXXXX..X.X..XX.XX.....X....X.X....XXX.XX.X.XX..XX..XXX..XXXXX...X...X.X..XXXXX.XXX..X.X.X..X.XXXX.X....XX..XXXX.XXX.XXXXX...X.X.....X...X.X..XXX..XXX.....X..XXXXX....XXX.XX..X.X..X.X..X.XX..X.X.....XX..\n\
XX..XX....X...XX...XXX.X.XX...XXX...XX.XXXXXXX.X.X.XXXXX.X.XX.X.X.X.X..XXXX.X.XXX.XXX..X.XX...XX...XX.XX..X.XXX.X.XXX..X.XX....XX...X.......X.X..XXXX.X.XXXXX......XX.X.XX.XX.....XXX..XX....X.X.X.X.......XXXX..X...X....XXX.\n\
XXXXX..X..X...XXXX..X..X.X.X..XX..XXXX..XX..XXXX.....X..XXX..X...X.XXXX...XX.XXXXX.X..XX.XX.XXXX.X.XX.X..X...X...X.XX.X.........XXX..X.X.XX..X...XXX.X..XX.XX....XX.XXX.XX...X.XXX..X.XX..X.X.X..XXX..X..X.XXXX.X.X.XXXX.X..XX\n\
X.X.X..X...XXXXXXX..XXXX.X.XX..X...X.XXXX.X.X..X..X..X.XXXXXXXXX.X..X........XXXX..X..XX.X.XXX...X....X.X..X..XXX.XXXXX.X...X...X.X.X.X..X.XXXXX.X.XXXXX..XXX..XXX....XXX.XXXX..XX....XXXX....X.X..XX....X.X...X..X.........XX\n\
.XXXX.X.XXX.....XXX.XX..X......X..XX.X...XXX.X..X..X.X..X.XX.....XXX.....X.XXX.XX.X.X...XX.X..X.XXXX..X.XXX.X..XX..X...X.X...XXX..XXX.XXX.X.X...XX...X.XXXX.....XX.X.X..X.......XXXXXX....XXX...XX.X.......XXXXX.X.X...X...XX.\n\
XXXX...XXXXX.XX.........XXX...X..X.XXXX.X.XXX.XXX..XX..X.XXX....XXXXX.X.XX..X..XXX..XXXXX.XX.XXXXXXX.XX.X..XXX.X.XXX.X.XXX....X.XXXXXX..X..XXX.X.X.X.X...X.X..XXX.XXX.XXXX.XX.XXXX.X..XX.XXX.X.XXX....X.XXX.X...XX..XX..X..X.X\n\
.X..XXX.XXX...XX.X..X.X..XX.X..X.XX.XX...XXX.XXX.X....XX.XXXX..X.X..X.X..X.X..XXX...XXXXXXXX.X.XX..X...X.X......X...XXX..X.X...XX.XXX.X..X..X...XXX.X.X...X...X..XXXXX.X...XX..XXX.X.XX.XX..XXXX.X.XX.X.XXX...X...XXXX....XXX.\n\
...X.XX..X.X..X.XX....X..XX..X...X..X..X..XXXXX....X.XXX.XX.XXXXX...X.XXX..XXXX...XX...XX...XX.....X.XXXX..X...XXXX..XXXXXXX.X...XXXXXX...X......XX.XX.X..X....XXX.X.X.....X..X.XXXXX..X.X.X.XX....X..X.XX...XXX.X...X..XXX...\n\
.XX..X...XXX...XX.X.....XX.X..XXXX.....X.XX.X...XX...XXX.XX....XXXXX....X.XX...XXXXXX.XXX.X.XXX..X..X.XXXX...XX.XX......XX.X.XX.X.XXXXX.XX.XX.XXXXXX.XXX..XX.X.X..X.XXX..X.X.XXX...XX...X...X.X......XXX...XX.X......X.X..XX..\n\
...XXXX..XX.XX...X..X.XX.X..X.X.XXX.XXXX.X.XXX....XXX..X...X.XX..X.X.X..XXX.XX.XXXXX...X..XXX..XX.X..XXXXXX.XX..XX.X....X..XX.XX.XXXXX.XX.XX...XX...X.XX..X..XXXX.X.X..XXX...XX.X.X.XX..X.X.XXX.XX.XXXX...X.X.X.....X.XXXX..X.\n\
...XXXX...XXXXXXX.X.XXXX.X.X.XX.X..XXX.X.X.XX..X....XXX.XX.X.X..XXXXX...XX..X.X.XXXX..X.X.XXXX.X..XX....X....XX.X....XXX.XXX....XX.XXX.XX.XX....XXXX.XXX.......XX..X..XXXX....X..XX.XXXXXX..X...X.XX..XX.XXX.X...XX.X.XXXX..X.\n\
.....X..XXX.X..XXX.XXX..XXXX...X.XX.XXX.X.XX.X.X.....XXX..XXX.X..XXXXX....XX..X.XX.......X...X.X.XX.XX...X.XX.XX..X.XX..XXXXXXXX.XXXXX..X.XXX.X..X.XX..XX.X........XXX..XXXX.X..X.XX.XX...X..X.XX..X..X..X...X.....X.X...X....\n\
XXXXXXXXX...XXX.X....X.X.XXXX..X.......XX.X.X..XXXX.X..X.X.XXXXXXX.X.X..XX..X.X..XX..XXX.XXX..XXXXX.X.X...X...XXXXXX....XX.XXX.XX.X..XX.X...XXXXXX.X..X.XXXX...X.X..XX.X.XXXXX..X...X..X.X..X.XXXXXXXX.....X..XXXX.X...XX.XXX.\n\
XXX..X..XXXXX.XX.......X.XX...XX.XXXX.XX..X..X.X.XX..XX.....XXXXXXX...X.XXXXXXXX.XX..X.XX..X..X.....XX.XX.XXX.XX..XX.XXXXX.......XX....XXXX...X.X.XX.X...X.XXX.X.XX.XX.XX.X.XXX.X....X.X.XX..X.X..XX...XX...XXX..X.X.X.XX..X.X\n\
X....XXXX.X..XX..X.XXXXX..X....X..X.XXXX.XX..X...X....X..X.X.XX..X.XX........X...X...X.XX..XX.XX.XX.X....X.XXX.X.XXX.X..X..X.XXXX.XXX.XXXX.X..X.....X.XXX..XX.X.X....XXX.....XXX.XX.XXXX...XX...X..XXXXX..XX..XX...X.X..XX....\n\
.X.XX.XX..XXX.X.X.X.XXX.X.X....X.XXXX.X..X...X..X......X..XX...XX.XX..X....XXXXXX.X.XX.X...X..X.X.X..X.X.X.X..XX..XX.X..X..XX.XXX........XXX.XX.......X..X.XXX.XXXX..X.........X...XX...X....XX..XX.X........XXX.X..XXXXXX.X.X\n\
.X...X.XXX...XXXX.X.X...X...X.XX.X.XX.XX.X...X..XXXXX..X.XXX.XXX..X.XX.X..XXX..XXX..XXX.X...XX..XXXXXX.X.XXXX.....XXX.X..X...X...X.X.X.X.XX....X.XXXXX.X..X..XXX..X..X..X..XXXXXXX....X..XX.X....X...XX.XX..X.X...X..........X\n\
X..X....XX.XXX.X......X.X.XX.X.XX.X.X.XX.XX..XXX..X.XXX...X..X..XX...XXX.XXX.X..X.XX.XXXX.XXX.X.....XXXXX..XX..XX.X.X.X...X.XX..X..X...XX.....XX.XX..X.XX..XX..X..X..XXX.X..XX...X.XX..XX.XXXXX..X..X.X.XX...X.XXX.X.X....XXXX\n\
.XXX.X...X.XXXX....XXXXXXXXXXXXXXX...XXXX..XX..XX.XX..X..X....XX.XX..XXX...X..X.X..........X.XXX.XX.X..X....XXXXX.X.X...XXX....X.X.....XX..XXX...X..XXX..X.....X..X...XXXXX..XX.X...XXX.X.XX.X...X.X.XXX...X..XXXX..XXXXXXXXX.\n\
XXXX..XXX.XXXX...XXX.X.....X.X..X.X.XX.XXX.XX.......XXX..XX.XX.X.XX...XX..XX..XXX.XXX.X...XX.X..XX.XX.X..XXX.X.XX.XX..X..XX.X...X.XX.XXX...XX..XXX....XX.X....XX..X.XX....X.X.....XXXX......X...X.X..XX...XX.XX..XXXXX.X......\n\
.X...X.XX.X.XX.X.X..X....X..X.X..XX..X.XX.X.....X.....XX..X..XXXXX.X.X....X....XX..XXX..XXXX.X.X.XX...X.X.XX.X.XX..XXXXX.XXX.......X.XX....XXX.X.X.XX..X.X..X.XX..X.X...........XXXX..X..X.X..XX...X.X....XXX..XX.X..X...XX...\n\
.XXX..XXXXX.XX.X.XXXX..XX.XXX.XX.X..X..X.X....XX.X.X.XX.XX.X.X...X.X....X.X.X..X........XX.XXX...X....X.XX..X...X..XXX.XX....X.XXXXX...XX.....XXXX.XX.X...XX.XXX....XX.XXXXXX....X.......X.XXX..X.XXXX..XX....X..XXXXXX.X.....\n\
...XXXX.X.X...XX.XX..X.XX.X...X.XXXXXX.X.XXX.X...XX.X..X..XX..XX.X.X.....XXXXXXX..XXX.X.XXXXXX..X......XX.XX.XX..XXX....X.....X...XXX..X.X.XX..X...XXXXXXX.X.X.X...XX..XXX.XX.XXXXX......X.X...X.XXX.XXX.XXX..X.XX.....X.X..XX\n\
X...X.X.XX.XX.XX..XXXX.XX..X....X..X.X.XXX.X.X.....X.XXX.XX..XXX.XX.XX.XXX...X.XX.X.X..X.X.X..X..XX........XX...XXXXXXX.X.X.XX.XXXX...XX.XXX.X..X.X.XXX.....X.X.X.XXX..XX.X.X.X....XX.X...X.....XXXX....XXX.XXXX.X.X...X.X..X.\n\
..X...X..X.X.XXXXX.X.X...XXX.....XX.X..X.XX.XXX.XX..X.X.XXX.XXX..XXX.XXXX.X.X.X..X...XX.X.XX...XXXXXXX.XX...X..XXX.X...X..X.X..XXXXXXX.X..X..XX.XX.X.XXXXXXX.XX..XXX...XX....X..X.XXXX.....XX.X.XXXXXX..X.XX.X.XX.X..X.X..X...\n\
X....XX.X.......XX.XX..X.XX.X..XXXX...X.X..XXX.XX....XX...XXX...XX.XXX.....X..X..X.....X..XXX.XXX...X......X.X.X.X.XXX...X..XXXXX.X..X..XXX.X.XXXXX.X......X.XX.X..X...XXX.X...XX.....X.XXXX...XX.X.X.X.X........XXXXX......XX\n\
XX..XX.XXXX..XX.X.XXX.XX.XX.XXX.X..XXX.XXX..X.X..X.X...XX.XXXX.X.XX..XXX.XXX.XXX.XX.XXXX.X..X..XXXXXXX...X.X...X.....X.....X.XX..X..X.X...X.X...X.XX.XX...X.X....X..XX.X.X.....X.X.....XX.X.X.X.XXXXXXX.X.X.XX...XXXXXX..XXXX.\n\
.X..XX..XXX.XX.X.XX.X....X.XX.X.XX.XX.X...X..XX..X.X..XX..X..X.X....XXX.XX.....X.XXX.XX.X...X.X.XXX..XXXXXXX...X.X.XX.....XX..XX..X.XX.X.XXX..XX.X.XXX.X..XXXXXXXXX...XXXXX...X..X.....XX....X.X...XXX..XX......XX....XXX.X.XX\n\
XX..X.X...XX..XXXXX..XXX.XX.XXXX..XX.XXXX.....X.X.XXXXXX...X..XX..XXXXX.XX.XX..XX...XXXXXX..X.X.X..X.X..XX...XX..XXXXXXXX..X.....X..XX.X...X...X..XXXX.XX.......XX..XXX..X...XX.X...X.X.X..XXXX.XXXX..X.XX.XXX.X.XX.XXXX.X.X.X\n\
X.XXX.XX...X.XXXX.XXX.X.X.XX.X...XX.XX.X..X..XXXXXXX...XXXX..X..XX.XX.XX..X..X..X.X.X..X..XX.XX..X..X.XX...X.XXXXX.X.X..XXXXXXX..X..XXXXX...X....XXXX......XX.X..X..XXX.....X.XX.X..XXXX.X.XX.XX..X.XXXXX.XXXX.XXX....X.X.XX.X\n\
X.....XX....X...XXXXX.XX..XX.X...X.X......X....XX....X..XXX..XX.XX...X.....XXXXX.X..XX...XX.XX.XXXXX.X.XX.......X..XXXX.....X..XXX..X.X...X.....XX..X.X.XX..XXXXXXX..XXX.X.X.XX.XXXXX........X.XX.X..X..XXXXX....X.....XXX.X..\n\
XXXX..X.X...XX.XX.XXX..X.X.X.X.X.X.X..X.XXX..XXX.XX..X.XX.XX....X..XX....XX..XXXXX.XX..XXX.X.....XXXX...XX.....X..X..XX.X..XX...X.XXXX....XX.XX.XX......XX...X...XX.X...X.X.X...XX.XX..XXX..XXXX..XX.XXX.XX.......X.XX..XXXXX.\n\
XXXX..X.X.X..XX..XX.X..X..X.XX..XX.X.....X.X.XXXX.XX.X.XX.XX.X.....X..XXX.....XX.X.XX.X.X..X..XX..XXX..XXXXX...XX.....XXXX.XX.XXX.XX.XXX.X.X.XXXX.X.XX.XX.....X.XXX...X.....X..XX.X..X.X.XXXXXX..X.X.XXX..X......XXX....XXX.XX\n\
.XXX.XXXX...X.X.X.XXX..X.X...XXXX.....XX.XXX.X..XXXXXXX.XX.XX.XX......XX...X.X.X..X....X..X.X.X.XXXX.XXXXX....XX.X....XXX.....XX.XX..XX.X..XXX.XX.XXX....XX.X.X.XXX....X.XX.X.X.X...XX.X..X......X....XXX..XXX...X..X.XX..XXX.\n\
XXXX.......XX.XX......X....X...X..X.XX.XX..XX.X....XX.X..XXXX.X.......XXXX.XX.X..X.....X.XX.XX..XX..XXX..X....X.........XX.XXXX.X.X.XX.XX...X...XX.X..XXXX..XX.X..X.X...X...X..XXX....X.XXXX.......X.XXXXX..X..XXXXXX..XX.XXX.\n\
X....XXXXX.XX.XXX..X..X.XX.XX.X.......X...XXXX..XXX.X.X.X..XXXXX..XX.XX.X.X.XX.X..X.XXXX.....X.X....XXX....XX....XX..X..X.X.XXXXX.XX.X..X.X.....XX.X.XX..XXX.X..XX.XXX...XXX..X....XXX.XXX.XXX..X.XX.XX.XXXXXX..X..XXX.X..X.XX\n\
...X.X.X.X...X.XXXX.X...XXXX..X.XX.....X.XXXX.X.X..X....X....XXX.X.X.X..XX..XXX...XX.X..XX.X.X.X...X..X.X.XXX...XX...X..XXX.XX...X.XXXXXXXXXXXX..XXXX...X.....XXXXX.XX.XX..X.X...XX.X..XX....XX..XXX.X.X.X.X.XXX...XXX.X..X...\n\
.XXXXX..XXX.XXXX...XX.XX...XX.XX.XXXXXXXXXXXXX..XX....X..X.X..XXX.XX......X..X..X.XX.X..XX...XXXX..X.XXX.X.X..X...X.XXXX..XX...XXXXXX.XX..X..X.XXXXXXX.XX....XX.X.XXXXXX.X.X..XX.X..X.XXXX.XX.XX..XX..XX.X.X.XXX..XX..X..X..XX\n\
XXXXXXX.X...XX....XXX..X.X.XX.X....X.XX.XX..X...XXXXXX..X.X...X...XX.X..X..X....X.X..X.X.X..X.X...XXXXX......X..XXX.XXX.XXXXXX...X.X....X.X......X.X..X.XXX.X.....X..XXX..XXX....X.....XXX.X.X.XXX..X......X.XXX.X.XXX.XX.X.XX\n\
XX.X.XX.X.XXX.X.XX....X..XXX..X.X.X.X.X...X..XX....X.....X..XXXX.X.XXXX..X..XXXX.XX..........XXX...X...XX.......XX......X...XX..X.X.X.XX......X.X...X.X.XXX.X..XXX.X..XX....XXXX....XX.....X.XXX.XX...X.X.XX..X.X..XXXX..X...X\n\
..XX......X...XXX....XX.X.X..X.X...XX..XX.X.XXX..XX.XX..X.X.X...X.XX..XX.X.X.XX.XXX.X......XX..XXX...X...X...XXXXX.XX.XXX.XXX..XX.X.....XX.X.XX.X......XXX.X.XX.X..X.X..XX.....X.XX...X.X.X.XXX..XX.XX..X..X.X..XX..XXX.X...XX\n\
.X.X..XXX..X.XX...X.XX.....XXXX.X.XX.X.XX....XXX.XX.X.X.XXXX.X......XXXX..X...XXX.X...XX..XXX...XX....X..X...X.XXX.XX.XXX.X......XX....XX.X..XX...XXX.X....XXX.XX.XXX.XXX.X.XXXX..XXX.X.XXX.XX.X.XXXXX.X.X..X....XX..XXXX..X..\n\
XXX.XXXXXX.X..XXXX.X...XX.........XX..X.XX.XX....XXXX.....XXXXX....XX..X...XX.XXXX.....X...XX.XX...XX....XXXX.X.XXX..XXX...XXXXX.XXXX..XX.......X..X..X...XX......XXXX.X.....XX..XXXXXXX.XXXXX.X.X.....XX.....X.X....XXXX.X.XX\n\
..X....X..X..........X.X.X..X..X.X..XX.X.X.XX..XX.X..X.X.XX..X...X...X..XXX..XX..XX...XX......X.....XXXXXXXXXX.XX..XX..X.......X...XX..XX.X.X.XXX.XXXXXXXXXX.XX.....X..X.X...XXX..XX..XXX....X....XXXX.X.....X.XXXX..XXX.X.XX.\n\
X.XXXXXX.XXX.XX.......X..X...X..X.XXXX.XX....X........XXXXX.X.X...X..XXX.X..XXXXX.X...X..X.X.XXXX..XX..X.XXXX.XX.XX..XX..XXX.X.X....XX.....XX.XX.X......XXXXX.X...XXX.XXXXXX..X.XX..XXXX...X.X.X...X.XX..X..X.X.X..X.X.XXXX..X\n\
..X....X.X..X.XXXXX.X..XX.XX...X.X..X..X.....X..XXXXXX.XXXX.XXXX.X.X..X.X...X.XXXX..X...X...X..XX...XX.X..XX.XX.X.XXXX.XXXX..X..XX...X..XX..X.X...X.XXX..X.XX..XX.XXX..XX..X.X.X.XXXXXX....X..X.XX.X..XXXX...XXXXXXXX.XXXXXX..\n\
X..X.XXXXXX.XXXXX.XX..XX..X...X.X.X...XXXXXX..XXXX.X.X.XX..XX.X...X.XX..X.X.XX.X.X.X.X.XXX.XX...XXX...X.XXX.X..X..X..X....X.XX..X.X..XXX.....X....XXXXXXXX..XX.XXX.....XXX.XX.XXXXX..XX..XX..X...X.X.X.XXX.X..X..XXXXX.XXXX...\n\
XX...XX.X.X.....XX..X.XXX.XXX...X..X.X..X.X.XX.XX...XX.XX.X.XX.XXXXXXX..XXXXXX.XXXXXX.X....XX.X.XX...X.X..X.XXX.XXXXXX.XX.X.XX..XX.XX..X.X.XXXXXXXX.X..X....X...XX..X.XX...X.X.XXXX..X..X.X..X.X.XX...X...XX.XXX.XXX..X..XX...\n\
.X.XX.X.X..XX..X..........X..XXXX...XX..XX.XX..XX...X...XX..X.X.XXX.XX.X...XXXXX.XXX..X.X.X.XX..XXXX...XX.XX.X....X.X.X....XX...X.....X.XXX....XX..XX.XXXX....XX.X...X.XX.X......X.X.XXX.XX...XXXXXXXXX.X..XX..XXXX.X....X....\n\
.X...XXXXX.....XXXXX.....X.....XXX.X.XX..X..XX..X.XXX.XX.........XX.XXXX..X.X..X...XX.XX.X..X.X.X....X...X.X..XX..XX..X..XXXXX.X..X.XX.XX...XXX.X.X.XXX...XXX..XXXX....X.X...XXXX.XX.XXX.XX..X.X.XXXX.XX.XXX.X.X.XX....X...X..\n\
..XX...X..X.X.X.X..X..XX...XXX.X.XX.XX.X..XX....XX.XX.....XXXX.XX.....X.X.X..XXXX..XX.X.X.X.X..XX.XX.X.X.XXX.X.X..XXXXX..X....X.X..XXX.XXX.X.X.......X.X....XXXX...XX.XX.XX...X...X.XX.XXXXX..XXX...X.XX.XX....X.X....XX..X...\n\
XXXX...X.X.XX.X.XXX.....X.X..X.X....XXX.....X.XXX.XX..X...X.X.X..XX.XXXX......XX...X.XXX.X...X..X..X....XXXX.XXX....XXXX..XX...XXXXXXX.XX..XX....X.XX....XX.......X..X.XX.XXXXX.XX.X.X.X...X.X..X.X.X..XXXX...X.X.....XX..XX.X\n\
XXX..X..X.X..X.XXXXX.XXX.X...X......XXX...X...X..XX.XXXXX..X.X.X..X...X..XX.XXXXXX.XX...X..XX.XX.X..X........X...X.X..XX.X...XX.XXXXX.XX...XXXX......X....X...X..X...X.XX..XXX...XX..XXX..XX..XX..X.X..XX.X...XXX.X....XXX..XX\n\
.X.X..XXXX..XXXX.X..X.X.X.X..X...X...XX.XXX...X.X..XXXXX.X..X.....X.X.....X..XX..X...XXXX.XXXXXX........X...XX..XXX.....XX...X..XX.....X.X.XX.X.XX.XXXX.XX..X..XX..XX..X......XX.XX.X.XXX..XX..XXXXXX....XX.X..X.XX..XX...X...\n\
XXX..XX.X...XX..XXXXXX.X...X.XXX.XX.XX.X.X..X.XX..XX..X...X.XX.X..XXX....X..XX.XX...X.....X.XXX.XXX..X.X....XXX....X.XX.X.XX.X.X...X......X.XX.XX.XX...X.XXXX.....X....X.X..XXX.XXXXXXXX...X..XX....X..XX.X...XXX.XX.X...X.X..\n\
.....XXX.XX.X....X..XXXXX.XX.X.XX...X..X..X.....XX.XXXXX.XXX..X.X..XXXX..X....XXXX.XX.X.XXXX...X.......X.XX.X.XX.XX.XX....X.XXX...X....XXXXXX..X.X..X.X....X..X...X.XX..X....X...X.XXX.XXX..X.X.XXX..XXXXXX.X.X.X....X.XXX..XX\n\
.XX...X..X...X.X..XXX...XX.XX..XXXXXXXXX..XX.X..XXX.X.X.X...X...XXX.X.XX.XX.X...XXXXX.XXX...X.X.X.XXXXX..X.....X..X.......XXXXX...X..XX.X.X..X.X.XX.XX...XX....XXXX..XXXXXX.XXX..XX.X.XXXXXX...X..X..XX..X.....XXXX.X.XX.XX..X\n\
X...X.....X.X.X.XXXXX..X...XXXXXX...X.X..XX..XX.X.......XXXXXXX.X.X..XX.XX..X..X..XX.X.....XXXXXXX...X.X...XX.X..X...X.XXX..XXX.XX.....XXX....XXX...X.X..X..XX.XX...XX.X...XXXX.X..XXXXXXXXX.X.XX...X...XXX......XX..XX..XX...\n\
..X.X.....XXXX.....X..X...XX...XXXX.X.XX.X.X..X..XX..XX..XX.XXX..X..X.XXXX.X.XX..X.X.X...X....XX...XXX.X.X.XX...X.X..XX....X.....XX.X.XX.X.X.X..X..XX...XXXX.XX.XXXXX..X.X.....XXXXXXXX.XXXXX.XXXX...XX....X.XX..X...X.XX.....\n\
.XXX...X...X.X..XX..XXX.XX.X...XXX.XXXXXXXX.XXXXX.....X...XXXX.X..X.XXX...XX.X.XXX.X.X..X.X.XX.XX.XXX.XX.XXXXX.XXXX.XX.XXX.XXXX..XX.XXX.XX.XX...X.X.X.....X.XX.XXX...XX...X..X..X.X..X.XX...XX.X..X.X.X...XX..XXX.....X.X.X.XX\n\
..X.......X...XXX..XX.XX.X..X.XXX.XX.XXX.XX.XXXX...XXXXX....XXX....XX.X..X.X.X..XX.......X.X..XX.X..XX.X...X.XX.X.XXX...XXXXXX.XXXX.XXX.XX..X...X.X......XX......XX..X.....X.....X.X...XX.XXX.X.X..X.X...X...X....X.X.X.X.X.XX\n\
XX...X.XX...XXXX.XX.X..X.XX.X..X........X.X.XXX..X.X........XXX....XXXXX.X...XX..XX.X.XX.XXXXXXXXX.XX.XX.XX...XX.XXX......X.XX..XXX.XXXX..XX...XXXXXX.X.X.XXXX....XXX..X..X..XX.X..X.XXX.X.XX...XXXXX..XX..X.XXX..XXXX.XXXX...\n\
.X.XXXX.X..XXXX.XX.X....X.X..X.XXXX...X..XXXX.XX.XX..XXXXX.X.XX.....X...X...XX.XXXX.X..XXX....XX.XXXXX..X.X.XX.XXX.X.X.....XXX...X.XX..XX.....X....XX.X....X.X..XXXXX.X......X..XXX.XX...XXX..XX.XX..XXXX.X.XX.XX...X.....XX.X\n\
.X........XX.X..XXX.X.XX..XXXX.XXXXX.XX..XX.XX...X..XX..X.X.X.X..X..X..XXX..XXX.X.XXXX.XXXX.X...X.XXXX........XX..XXX..XX...XX.....X..X.X...XXX.XX..X..X.X..X..XXX.X..XXX.X...X...XX..X......XX.....XXXX.X.X.X.XXX.XXX...X.XX.\n\
..XX...XXXXX..X..X..XX.X...XXX...X...XXX.......XXX.XXX......X..X.X..XXX..XX.XXX.X.XXX.X..X..X.XX.XX.XXX.XXXX.X.X..XXX.X.X.X...XXX.XXX.XX...XX.X.X..XX...XXXXXX.......XXX..X.X..XXX.X.X..XXXXXX......XX.XX....XXXXXXX.XXXX....X\n\
.X.XX.X.XXXX.X...XXXX..X.X.X.XX..XXXXXX..XXXXX......XX.XXXXXX...XX..X..X..XXXXX.X.X..X..X.X.XX...XXXXX.XX...X.X.XXX..X.XXXXX..X.XXX.X..XX.X...XX..X.....X.XXX..X..XXXXX...X..XXX.XXX.XX.XX..X...X...XX....XX...XX....X....X...\n\
XX..X.XX..XX.X.X..X..X.XX.XXX.X..XXXXXXX.XXXX.X......XXXXX..X...X...X.XXXXXX.XXXX.X...XX...X..XXXX.X..XX.XXX.XXX....XXX..XXXX..X.XXX.....X.X.X.X.X...X....XXXXX.X.XX....X.X.X..XX......XX..XXX.XXX.X...X.X.....X.X.X.X..X..XXX\n\
.XXX.X..X...XX.X.X.X...XXXXXX...X...X.X.....X...X..XXXX..XX.X.XX...XX....XX.XX..XXXX...X..XX.XX....XX.X.XXX.X.XX....X..XX...X.XXX...X.X...X...X..X..XX.......X..X.XX....X.XX.XX.X....XXXX.X...XX..X.XXXXXX..X.XXX.XX.X.X..X...\n\
...XX..X...X..XX...XXXXX..XXXX.X......X...X.....XXXXXXXX...XX......X..X..XX.X....X.X......X..XXXXX...XX.XX.X..XX.XX.X.X.XX.X.XX..X.X..XX.XXX.X..XX..XX....X..XX....XXX.XX...X.XX..XXXX...XX.XXXX.X..X...X..X.XX.XX.X.......X.X\n\
.XXX..X.X...XXXXX.X.X.X..XXXXX...X.X....X.XX.XXXXXX...XX.X..XXXXXXX..XXX.X.X.X.XXX..XX.X.XXX.X.XXXX.XXX....X.XX..XX.XXX..XX...X.X.XXX..XX...X.XXXX.X..X.XX.X..XXXX..XXX.X...X....X.X..XX..X..X.X..X.....XXX.XXX....XX..XX...X.\n\
X.XXXXXX..X.XX....XXX.XX.XXXX.XXXX.XX.X.X.X.XX.X..X.X..X.....XX.X...X....XXXX..XX..X.....X.X.XX......XX...XX.X...X.....XX.X.X.X...XX.XX.XXXXXX....XXXX..XX..XXXX....XX...XXXXXX...XX...XXXXX.XXXX.XX..X.XX.XX.X.XXXXXX...XX.XX\n\
...XX..X.XXX..X.XXXXXXXX..XX.X.X...X.XXXXX.XX..XXXX..X.X..X.X.X..X....X...X.X.......X..X...X...XXXX.X.X..XXX.....XXX...X..X.XX..X...X.X.XXXX...XX..XXXXXX.X.XXX....X.X.X...XXXX.XXX.X.X.XXX.XX.X.XXX.XXX...XXX......X...X.X.X.\n\
XXXX..X.XXX..X..XXX.XXX.XX.XXX..XX.....XX.X...XXX...XX......X..XXXX..XX.....XX...X........XXXXXX.X..XXXXX...X..XXXX.XXX..X.X..X.XXXX..XX.X.XX..X.X.X.XX.XX.....XX..X.....XX....X.XXXX....XX....XXXX.XXXXXXXX...X....XX...X...X\n\
X.X..X.X....X..XXXXX.XXXX..XXX.XX...X.X..XX.XX..XX..X.X....X.X....X..X...X.XXXXXXXXX.XXXXXX.X...X.X.X.....X.X.X.XXX.XX..X..X..X...XXX..XXXX.X.X..X.XXX..X...XX..XX.X....X...X....X......XX.X.X...XXX...X.XX..XXXXX.X.XX.X.X...\n\
XXX...X.X..XXX.XX..XX.XX.X.X..X..XXX..X.X........XX..XXX..X.XXXX.XXXX.XXX....XXXX.XX..X..X.XXX.X..XXXX..XXXX.XX.....XX.XX..X.X.XX...XX..XX..X..X..XXX...X.XXX.X.X..X......X.XX..X..XX..XX.X...X.XXXX.X.XX..X..X..XX.X....X.X.X\n\
XXX.XXXX...XXXX........X..X..X.....X...X..XX....X.XXXXXX..XXX..X.X....X...X.XX.....XX.X...X.X.X.....XXX......X.XX.XXX.XXX...XXXX.XX..X.XX.XX..X..XXXXXXXX.X.X.XX.X..XX..XXX.X...XX.X.X..XXX..XXX.X.XX.X.XXX.XXXX..X...XX.X.XX.\n\
.X.XX.X.XX......XXXXX.XXXX..X...XXXX.X.XX..X...X.X.XXXXX.XXXXXX..XXX.XXX..X...X......X...XXXXXX.X.X..X.XXXXX.XX...X..XX.XX...XX.X..X.X.X...XX...X....X.XX.X.XXXX.X.....X..XXXXX..X.....XXXXXX..XX.XX.X...X.XXX...X..XX.X.X.X.X\n\
..XXX...XXX..X.XX.XXX.X.....X.X.X.XX..XXX..XXX.X..X.XXX.X..X..XXX..XXXXX.XXX....X.X.X....X..XXXX.XXX.XXX.XXXX..X..X..X.....X.X.X.XX..XX.X..XXXX.X..X..XX.X..X.X.X.XXXXXX..X...X.X.XX.X......XXX...XX..X.XX..XXX...X..XXXX.XX.X\n\
.XX...XXXXX....X..XXXX..XXXXXXX.XXX....X.XX..X..XX..XX..X...XXX...X.X...XXXXXXX.XX.X.XX..X.X......XX.XX.XXXX.XX.XXX..XXXXXX.....XXX....X..X.X........XXXX.X.X.X..X.XXXX.XXXXX..X..XX.X..XX.XXXXX..X.X.X.X...X.XX..XXXX.XX.XX.X\n\
XXXX..XX..XX.X.XX.X..X.XX....XXX...X.XX....X.XXXXX.XXXXXXX.......XXXXX.XXX.X.XXXX....XXX..X..X....XXX.X.XX..XXX.XX.XX..XX..X..XX.....XXXX..XXX..XXXX..XXX....XX..XX..XX.XXX.XXXXX.XXX..X..XXX.X..XXXX...X.XXX...X.XX...XX.XX.X\n\
...XXXX.X..XXX.X..X...X.....XXXX...X.XXX.X...X.X..XXXXXXXXXXXXX.X.X..XX..X..X..XX..X...X.X.X......X..XX...X.X..X....XX....X.X..XXX.X..X.XXX..X.X.....XXXX..XX.X.XX...XXX.XX.XX.X..XXXXXX...XXXXXX..XX.X..XX....X...XX..XXXX..X\n\
...XX...X..X.XX...X....X...X..XX..X..X.....X..X..XX.X.X..X.X..XXX.X..X..XXXXXXXXXXX..XXX.X..X.....X.XX...XXXX.X.X.XX.XXXXXX.X.XXX.X..X.X..XX.XXX..X.XX.X......XX.X.XXX..XXXX.X.X..X...XXX.XX.XX.XX....X.X.XXX...XX.XX.X..XXX..\n\
....X.X.X..XXX...XX..X.X.XXXXX.XX.X..X.X...X..X..X.XXXX.X..X.X..XX...XX......X......X.XX....X..X...XXX.X.X..XXXXXX.XXX...XX.XX.XXXXXX.....X...........XXX..XX...XX..XXX.XX.XX.X.X.XXXX.XX.XX....XXX.X...XXXXX..X....X..X.XX.X.\n\
...XX..X.XXX..XXXX..X...XXX..X...XXXXXX.XX.XX.X...XX....XX..XX..XXX.XXXXX.X..XXX.X.....XXXXX....X.XX..X.X.XX....XX.X.......X..X.XX.......XX....XXX.X.XXX....X.......X.X......X...XX.XX...X.X....XX.....X.X..XXXX..XXX..X.XX.X.\n\
..X.XXX..X....XX..X.XX.X.....X.X.....X.X.X.X...X.XXXX...X..XXXXXXXX...XXXX.X.X.X..X..XXX...X.X.X..X....X...XX.X.X.XX.XXXX..X.X.X....XX.X.X.X......X...X.X..XXX.XXXX.XXXX...XXXX.XXXXX.XXX..X....X..XXX..X.XX.XX.XXXX.X...XX..X\n\
X..XXX..X..XX...X.X.XX.XXXXXX..XX..X..XXX.X.X.X.XX.XXXX..XX.XXXX...X.XX...X..X.XXXXXXX..X.XX..XX...XXXXX..XX...XX.XX.XXX.XXX.XXXXXX....XXX..XX..XXXX...XX...X.X.XX....XX.XX..XX....X.X..XX.X...XX...X.X.X.XX.X..XXXXX...XXXX..\n\
.XX..XX...XXX.X..X.X.XXX.XX...X.....XX..XXXXX...X....X..........X.XX.X..XXXX.XXX.XXX.XX.X...X.X.XX.XX..XX.X.XX.X.XX.XXXXX.X.XX.X.XX.X.X...XXXXX....X.X.XX.X.X.XXX....XXXXXXXX...X..XX.XXX.XXX.....X...X.XX.X.XXX.X..XX.XXXXX.X\n\
XX.XXX.XXX..X.X......X.XX....X.XX..X.XX.XXXX..X....XX.X..XXX.XXX..XX..XXX.XX.XX.XXX..X..XX.X.XX.XX..X..XX.XXXXX..XX.XX....XX....XX.XX.X.X..XXX.X.XX....XX.XX..X..X.....X.XXX.XXXXX..X.X.XX..X.XX.XXX...X.XX..XXXXXXX...X..XX..\n\
XXX.XXXXXX..XXXXX...X...X...X.X.XXX.XXX.XXXX.X.X.....X..XXX.X.XX..XX...X.XX...X.XX.XX..X..X....XX.X.X.X..X.X..XX......XX.X.XX...XX.XXX...X..XXXX...X..XX.X.XX.X.X...XXXXXXX..XX....XXX.XXX...XX.XX.....XX.....X.XX.....X..XXX.\n\
.X...X..X.XXX......X...XX...X.X..X.XXX..XXXX..XXX.........X.XXXXX..XXX.XX.X.X.XX...X..X.X.XXX..XXX..X...XXX..XXX.XXX.XX.X..XX.X.X.XXX.XX..X.XX..XXXXXXX.X.X.X.XXXX.X.X.X.X.X..XXXXXXX.XXXX.XX...XXX..XX.XX..XXX..XXX.X..XXXX..\n\
XXX..XX..XXXX..XXX.XXX...XX......XX..XX..X..XX...XX..XXXXXXX.X.XX...X..XX...XXX.XXX.XXX.XX..XXX.XXXX.X...X.X.X..X.XX.X..XXXX.XXXXX.X.XX.X...X.....X..XX.X..XXX............XXX.X.XX.XXX..XX.XXX.XXXX.XXX.X.....X.XXX...X...XXX.\n\
XX.XXX.X.X..X..XXXX...XX.X.XXX.X..XX....XX.X.X.XX...X.XXXX.X.XXX...X.............XXX..X...XX.XX.X..XXX..XXXX.XXX..XXX...XX...XXX....XXXX..XX...X.X..X.X......XXXXXXXX..XXXXXX..X.XXX...XXXXXX.......XX.XX..XXX....XX...XXX.X.X\n\
X.X.X..X....XX.X....XXX.XX....XXX.XX..X.XX..X..XXXX..XXX........XX.X..X...X..XX.X.XXXX..X.X..XX..XX.XXXXXXX.XXX.X.XXX...X.XX.X..XX.X..X.X....X.XXX..XXXXXX.X...XX..X.X.X.X.XXX.X...X.XX.XX...X..X.XX.XX.X..XXX..X.X...XX.X.XXX\n\
.XX.XXXX....X....X.XXX.XX.....XXX..X...X..X.XX.XXX....XX.....XXXXXXX...XX..XXXX...X.....XX.XX.XX..XX.XX.X..XX...X..XX..XXXX...X..XX....X.XX.X.X..XX.....X......X..X..X.X.XXXX.X...X.X.XXXX....XX.X..X..X...X...X..XX..XX.X.X..\n\
.XX...XXXX..XX..X..X.XXXX....X..XXXX.XXX.XX.XX..XXXXXX.X....X.XXXXX....X...XXXXXX.X...X.XX.XXXXX..XXXX.XXXXX.XX....X.X.XX.X.XXX.XXXX.X.X.....XXXX...X..XX.X.X..XX.XX...XX.X.XX...XXX..X..XX..XX.X.XX.XX......XXX.X.XX...XXXXXX\n\
X..X.X.XXX....XXXXXXX.X...X.......X...X.X...X.XX.XX.XXXXX..X....XXX...XX.XXXXXXXXXX..XXXX.X...X..X.X.X.XX...X..X.X..XX.X..XX.X....X.XXX.X.X.XXXXXXX..X.X.XXX.XX.X.X.XXXX.X....X...XXXX.....X..X..XX...XXXXX.X.XXX...XX.X.XXX.X\n\
XX.X..X....XX..XX..XXXXXX...XXX...X.X..X.XXXXX.X.XX.X.XX...X..XXXX.XXX.XX.....X.X..XX..X...XX.XX..XXX.XXX.X.X..XX..X.X...X..XXX..X...X.XX..X.XXXXXX.XXXXXX..XX.XX....XXX..X.XX...X..X.X......X..XXX..X..XX.XX.X.XX..XX.XXX.XX.\n\
XXX.X.XXXXXXXX...X..X..X.XXXXXX.XX.X.......XX.XXX...XX..X.X.X.XXX.X..X.X.X....X..XX.XX..X..XXX.XX.XX.X..XX....X...X...XXX.XX...X......X.....X...X.XX.X..X.X..X.XX..XXXXXX.XXXXX.XX.....X..XXX.XX...XX.X.XX.X.XXX...X.X..XXXX..\n\
..XX.XX......X...X..XX.XX..X..X..X..X.XXXX.....XXXX..X..XXXXXXX...XX..XXX..XX...X.X.X...X.XXXX..X.X..X.XXX.X...XX...X...X..XX.X.XXXX...X.XX.X.....X..XXXXXX....XX.X....X.XXXXX..X.....XX....X.XX...XXX....X.X...XX..X.X.X..XXX\n\
..XX....XX..XX.X......XX..X.X.X..XX.XX..X.XXX.XX..XX..X..XX.XXXXXXX.X.XX.XXXXXX.X..X....XXX........X.XX...X.XXXXXX.XXXXXX..XX.XX..X..X..XX...X.XX.XX.....XX...X.X.X..X.X.X....X..XX.X...XX....XXX..X.X..XX.X...X....XX.X.XXX..\n\
....X.XXX.XX...X.XXXX..XXXXXXX.XXX..XX..XX.XXXXX...X.X.X.XX.X.XX..XXXXX.XXXXX.XXXX..XXXXX...X....XX..X.XXX..X....XX..XXXXX.XXX..X.XXXX.XX.XX..X.X........XX..X..XXX.X..XXXX.XX.XX.X.X.XXX..X...XXXXX.X...X.XX..X...XXX....X...\n\
X..XXXX.X...X..XXXXXXX.X.X...XX.X...X.XXXX....X.......X....X.X.X..X.X.XX.X...X..X...XX...X.XXX...X.XX..X.XXXXXX..X.X...X.X.XXXXXX.X..XX.X..XXXX.XXXX..XX.XX..X..X.X..XXXX..X..XX...XXX...XX..XX..XXX..X..X....XX.XX.XX..XXX...\n\
X..X..XX.X.XX..XXXXXX..X.XX..XX....XX.X..X.X..X........XXXX.XXXXXX.XXX.X.X.XX.XXX.X..XX..XXXXXX.X..XX...XX.XXXX...X..XX.....X.X..X..X.X.......XX.X..XXXXXX.X..XXXX...X...X...XXXX.X.X.....X.XXXX.X....X......XXXXX.X...X.X....\n\
XX.X..XX..X...XXXX...XXX...XXX..XXX.X..XX.X.X.XX.XX.X....XXXX..X.X.X.X.X.XX.XX.X.X...X...X.XXXX..X..XXXXXX...XXX.X..XXX..X..X.......XXX...XX.X..X.XXX.XX.XXX....XXXX.XXXXXX.XX..XX..X.XXXX..XX..X....XX..XX.XX.X...X.X..XXX.X.\n\
...X..X..X......XX.X.XX..XX.X.XXX...XX....X.X....XXXXX.XXX.X..X.X.X...XXXX..X.XX.X.X.X......XX..X....XXXX....X...X....X.XXXXX..XXXX..XXX.XX.X.X..XX.X..XXXX..XXXX.X.XXX.X.X.XXX.X..X..X.X...X.XXX....XX.XXXXXXX.XXXXXXXX.XXX..\n\
.X.XX...XX.XX..X...X...XX.XXXX...X.X.XXXXXXX.XXXX.X.X..XX.X..XXXX.XXX...XX....X...X..X.X.XX.XX.XX.X.XXX.X.X..X.X.X........X.......XX......X..XX..X.XX..X.X.XX.X.X...X....XX....X.....XXX..X..X....XXXX..XXXX..XXX..X.XX.X.X...\n\
X.XXX..X.XXX..X.XXX.X.XXX..XXXXXX..X.X.X...X.XXXX....XXX.X.X.X.X..X...XXX..XXXXXXXX....XXX.XXXX.XXXX.XX.X.X.....X..X.X..X..XX.X.XXXX....X.XX.X.X.X..XXX.XXXX....X.X.XX.X..X..XX..XXX.XXX.XX.X........X..XXXXX.XX.X..X.X..XX..X\n\
XXX..X.X.XX.X.XX..XXX.X.XX.XX.XXXXXXXX....XXXX.X.....XX.XXXX..XXX...XXX....XX.X.X..XXX..X...X.X.XXXX.....X.XXX.......XXXX..X.XX...X...X..X.XX...X.X..XX.X..X.X.X.XX.XXX..X...X....X..XXXX.XXXX........X...X...X.XXX....X...X.X\n\
....X.XX.XX.X......XX.X.X..XXXXX..X.XX..XXXX.X..XXX.XXXX.X..X.X.XXX...X.X.XX.XX.XX.X.....XXX.XX..XX.XX.XXX...XX..X.XX.....X....X..X..XXXXX....XXX.X...XXXX.X.XX..X.X.X.X..XX..XX.X..X..X.XX.XX.X.X..XX...X..........X.X...X.X.\n\
..X..X...XX.X.XX.X.XX..XXX.X..X.X..XX..X.X..X..X....X.X.X..XX.XXX..X.XX.XX.....X.XXX..XXXXX.....X.X..X.XX.X.X..X.XX..XXXXX..X.....XXX.XX.XXX.X....X....XX....X..X.....XX.XX.X..X.XX..XXXXX.XX.X.X...X...X.X...X.X..X..X.X.X..X\n\
...X....XX...X..XX.XXX.X.XXX.XX..X....XXX.XX.XXXXXXXX..XX..X.XXXX..XXX.X.XX.XX....X.XX.......X.X.X..X.X..XX.X.X.X...XX..XXXX.XX.XX...X.X.XXX..X.XX...X..X.X.X.X..X.XXXX..XXXX.....XX...XX..X.....X.XXX..X.X.XX..XXX...XXXX.X..\n\
.X...X.X.X.XXXXX...X...XX.X.X..X.XXX....XX....XXXX.XX.X.XX.X..XXX...XX..XX.X.X..XXX..X.....XX...XXX.X....XXXXXX.X.....XX.X.XXXXXX..X.XXX...X.XXXXX.X....X.XXXXXXXX.....XX...XXX.XX.X.X......X.XXX.X.XX.XXXXXXXX.X.X..XXXX..XX.\n\
..X..XX..XX...X...X.X....XX....XX.X....XX.XX.XX..XX.XX.X.X..X.X.XXXXXX...XX..X.X.XX..XXX..X.X...X.X.XXXXX.XXXX.X..X.X.X.XX.XX..X....XX.XX.XX...XXXX.XXX..XXXXXXX....X.XXX.XX.....X.XXXXX....XXX....X......XX.X..X....X.....X.X\n\
.X..X.XXX.XXXX.X.X.XXXXX.X..XXX.....XX.X.XX..XX..X.XX.XX..XX....XXX...X.X.XX..X..XX..X.....X..X.X...X.....XX.X...X.XXXXXXX.XX.X..XXXXXX.....X.XXXX.XXXXXX...X..XXXX..XXXXX.XXXX.X....XX.XXX...X..X..XX..X..X...X.XXXXX..X.....\n\
X.X.XX..XX....XXXX.....XXXX.XXXXXX....X.....X.XX..XX..XXXXX.XXX..XXX.X.XX.XX...X..X.......X.XXXXXX...XXXX.XXX.XXXX....XXXX.X..X.X.XXXX..XX..X..X....XX...XX.X.XX.XX..XXXXX....X..X.X.X.XXX..XXXXX...X..XXX..XX.......XXXXX.XX.\n\
X....XX.........XXX.XX....X.X...X.X.....X......X..X...XX..XXXXX.X.X.XXXXX....X..XXX.XX..X.X......XX....X..X...XXXX.X..XXX..X...X.XXX...X.....X.X..X...X..X.XXX....X.XX..XX.X..X.X.XX...X.X.X.XXXXX.XXX..XX.XX.X.X.XX.XX....XX.\n\
.XX..XXXX.X.X.XXX.X...XX...X..XX...X.XXXXXXXX..X.X..XXX.X.X..XXX.X..X..XXXX.X....X.XXX.X.XXX..X...X...X.X.X..XXXX......X.XXXX.X.X....X.X.XXXX.XXXXXXXXXXX.X...X.X.X...X.XXXXXX....X.XXXXXX....X.....X.XXXXXXX...XXXXX.XX.X..XX\n\
..XXX.X...X.XX..XX..X...XXXX.....XX..XX.XXX.XXX.....X.XX.XXX.X.XXX..XXXX...X..X.XXX.X.XXXXXXX...X..X..X..X...X.X..X.X.X..X.XX.X..X.XXX.XXXX.X.X.X.X.....X..X.XX....X.XX.XX.XXXXX.......X.XXX..XXXXX.....X.....XXX..X.X.XX..XX.\n\
X.XX..X.X.X....X.X..XXX.X.XXXXXX.X.X....XX..XXXX.X.X..XX...XXX.X...X.X...X..XX.X.XXXXX...XX.X.XX...XXXX.X....XXX..X.XX.XX....X.XX....XX.X..XXX.XX...X.X.....XXXXX...X.XXXX.X.XXXXX......X.X.X...XX.XX.X..X...X..XXXXX...X.X.XX\n\
XXX..X...XX.....XX.XXXXXX...XXX..X.XXXXX..X.X.X...XX..X...XXXX.XXX.X.X.X.X.X.X..XXX...X.XXX..XX....XXXX..XX.XXXX...X...X.XXXXXX..XXXXX.X....X.X...XX.XXXX..X.XXXXX.X.X.X..X....XXX....XXXX.X...XXX....XXX.X.....XX....X....X..\n\
XX.X.XXX.XXXX.XX.X.XX....XX.X.X....X.XXX.XXXXXXXX....X.XX..X.X....XXXX..XX..X.X..XX......X.X..X.X.X.XXX.X..X..X...XXXXX...XX..XXX.X..X...XX..X.XXXX..XXXXXXXX..XXX.XX....XXX.XX.X.XXXX.X...X........XX...X..X...X...XX.XXX....\n\
XX.X..X..XXX.....XX..X.XXXX..XXXX.XX.X...X.XX..X.X.X.XX.XXXX.....X.X.X..XXXX...XXXXXX.XX..XXXXX..XX..X...XXXX.X..X..X.XX...XX..XX.X.XXXXXXX...X.XXXXXX..XX..XXXXXX.XXX.XX..XXXX.X.XXXX......XX..X...XX.X..XX.XXX.....X.XX..X.X\n\
.XXXX.X....X..X.X...XX.....XX..X..XXXX.XX.X....X.XX.XX.X.XXX...XXXX.X.....X.X..XX.X...X.X...X..XX.XX..XX.X.XXXX....X.X.X.XX...X.X...XX..XX.XXX..X..XXX.XXX....XX.XXX......X..X..XX..X.X....XX.X.XX.X..X.....X.X..X.XXX....XX..\n\
.XX....X....X.X.X.X.X..XX.XXX...X..XX.XXX.X.XX....X..X..XX...X..XXXXXX.X....XX.X.XXXXX...XX...X..X.X..X.X..XX..X...X.X..XX.XXX..XX.X..XX.XXXX..X.XX.XX.X....XX.X.XXXXX.XX..X..XX..X..X...X......XX..XXX..XX.XX...X.X..X.X..XXX\n\
.....XXX..X....X.X.XX.XXXX......XXX...XX..X...........XXXXXXXX.XXX.XX.XX.X.X.XX.....X..XXXXXXX.X.XX.X.X..XXXX.X.X...X..X...XXX.....XX.X..XXX.X..X..XX.XXX..X.X..XXXX.XXXX..XX...X.XXXXXXX.XXX.X...X.X.X.X...X..XX.X.X...XXX.XX\n\
...X...X..X...X..X..XX...X.XX.X.X.....XXXX.XXXXXXXX....X..XXXX.XXX.XX..X.XXXX.XXX....X...X.X...X.XX.X.XX..XXXX..XX..X.X..X...X.X.X.X.XXXX.XXX.X.X.X....X..XX.XX.XX......X...X..XXX..X..X..X....XXX.X.XXX.XXXXXXX..X.X..X.XX...\n\
....XX...XXX..XXX.XXX...X.....X..X...X.XXX....XX....XXX.X.X...X.XX..X....X...X.XXX.X...XXXXXX.X..X..X...XXX.X...X.XXXXXXXXXX..XX.XX.XX..X..X....X.XX.X....X.X...X..X....XXXX..XX...X.X.X.X.XX..X.XXXX.........X....XXXXXXXXXX.\n\
X.....X.X...X....X..X...........XX...XX.XX....X..X.XX.X...X...X...X...X.X.X..XX.X.X..XX.X.XXXXX.X....X...X..X.X...XXX.XXX...X.X....XXX.....XXXXXX.XX.X.X..XXXXX...X.X.X.XXX.X.X....X..XX....X..XX..X.X......XXX.........XXX.X.\n\
............X.X..XXX..XX..X...XXX.XX..XX..X.X.X..XX..X....XXX.X..X..X.XXXX.....XXX..X.XXX.X.X..X.XXX.X..X.X.XX.XX.XXX.X..XXX.X..XXX..XXX...XX.X.XX.XX.X...XXXX..X..XX....XXXX..X..X...XX.XX....XX.XX...X.X...XXXXXX.XX.XXXX...\n\
X.X.X.XX.X.XXX.X..X...XX.X..X.X.XX.X..XX........X..X..XXX.XX.XXX..XX.......X.....X..X...XXXX.XXX..XXXXX.X.X.XX.XX..XX...X.XX..X..XX.XXXX..XX.XX..X..XX..XX.XXX...X..X..XX.X..X....XX.XX...XXX...XXX..XX.XXXXXXX.X..X...XXXXX.X\n\
.....X........XX..X..X.X...XXX....XX.X.X...XXXX..X.....X.X..XXX..X.X.X..XXX.X..XXX..X...XX........XXXX...XXXXX....XX....XXXXXXX..X...X.X.X...X.XX.XXX...XX..XX..XX.X.X.X...XXX......X...X.X.X.X....X..X.X......X..X.X...XXX..X\n\
.XXX..X.X.X......X.....XX....XX.XXXXX..XX.X.X..X.X.X.XXXXXXX..XX....XXX..XXX.XX..X...XX....XX.X.XX.X..X...X.XX..XXXX..XX.XXXX.X..XXX.XXXXX.X...XXXXX..XXX.X..X.X..X.X...X.XX.X..X.XXX...XX.X.XXXX.XXX.X...XX.XX..X.X.....XX.X.\n\
XX..XXX.XXXXXX.X...XX.X.X.XXXX.XX.....X.X.XXXXXXX.XXX.XX..X.XXX...X.XX..X..XX.XXX.X....X...X.X.XX.X...XX.XXXXX.XXX.XXX.XX.XXXXXX.XXXX..XXX...X.X..XX.XX.XX.XX....XX...X.XXX..XXXX.XX.XXXX.X.XXXXX..XX.XXX..XXXXX.X.XXX..XX.XX.\n\
..XX..XXX..XX.XX.X..XX..XX.X.....XXX.XXXXXX.XX..XXX....X...XXX...X.X.XXX.XXX.XXX.X.XX..X.XXX.XX...........X.X....XXX.XX...X...X.XXX.....XXX.X....XXX..X..X..X..XX..XX.X.X..X......X.XXXX..X...X..XX.XXXX.XXX..X..X...XXX.XXX..\n\
...XX.XX...XXXX..XX.X.X.X..XXX.XXX..XX..XXX.XXXX...X.XX...XXXXXX...............X.XXX....XXX...X...XXX.X...X.XX..XXX.XX...XX.X.XX.X..XXXX..X....XXX..X.X.XXXXXXX.X.X.X.....X.....XX.XX.XXX...X.XX.X.XX....XXX....XXX...X....XX.\n\
XXXXXX.XX...XXXX.XX.X.XXX.X.X...X..X.....X.XXX.X.X.X.XXX...X...XX..XXX..X.XXX....XXX.X.X.XXXX..XX.XX.X.X...X.X.X.X.....X..XXX...X......XXXXX...XXXX..XX...XXX.XX.X..X..X.XXXXXXXX.XXX..XX.X.X..X.X.XXXX.X...X.XXXX.X.XX.X.XX..\n\
X...XX..XX.X.X..XX.XX.XX..X...XX.XXXXX.XXX.XXX..XX.XX..XXXX...X..XX.XXX...X.XXXX.XX.XX.XX..X..XXX...X.X.....XXXXXX.X.X.X....X.X..XXX.X..X..XXX.X...XX...XX...X...X.X.XX..XX...XX.XXXX.X...X....X...X.....XX.XX.XXX.X.XXX...X.X\n\
XXXXXXX.X.XX........XXX..X.X..X.XX...X.X..XX.XX...XX.XX..XX.X.X..X..X..XX.X.....XXX.X.XXX.....X..X...XX...XX..X..XX..X.XX..XX..XX...XX..X.....XXXX..X.X..X....XXX.XX...XX.X..XX.X.X..XXXXX.XXXX....X...X..X..XXX...X..X..XXX.X\n\
X.X..XXXXXXXXX....XX.XX..XXX.XX........X....XX.....XXX.X.X.X.X.X..XXXX.X.X.X....X..X...X.XX...X....X..X...X..X.XXXX.X.XXXX.XX.....XXXXXXXX..XXXX...XX.X...X....X.XXXXX.XXXXX..X.XXXXXXX..X.X.XXXXXXX.X..XXXX.XX...XXXX.XX.XX.X\n\
XX..X.X......X.X..X....X.X.XX..X.XX......XX.XXX..X..XX...XXX..X..X...XX...XX.XXXX....X....XX.X..X..XX..X..XXX..X...XX..X.X..X...XX..XX.X.X....X.X.X...X..XXXX..XXX.X..X..X..X..XXX.XX.....X..X.XXXX...XX.X..X..X..XXX.....XXXX\n\
XXX...XX.X.X.XX...X..XX....X.X..XXXX....XX.X..XXX..X.XXX.XXX.X.XX.XX..XXXX.XXX.X..XXXX.XX.XX.X.XXXXX.X..XXX..X..XX.....XXXX.......XX..X..XXXXXXXX..X.XXX.X.XXX..X.XXXX.X.X...XXX.XXX.XXXX...X..XXX.XXXXXXX.X.X.XX...XX..XXXX..\n\
.XX...XX.X.XX.X....X..XXX.XXXX..XXX..X.X..XX...X.X.XXXXX.X.........XXXX...XX..X..X..X.X.....X..XX...XXXX.XX.XX..XX....XX.XX.....XXX...X.XX.X..X...XX.......XX.XX...XXX.XX.XXX...X.X.XXX...X..XX..X..XX.X.XX....X.XXXX.X...X.XX\n\
X.X.X..X.X.XX.XX..XXX.X.X...XX....X.XXXXX...X...XX.X.XX.XXX..XXXXXXXXX.X.X...XXXXX..XXXXX...XX..XXXXXXX...X.X.X.XXX.XXX..XX...X....X.....XX.X....X.XX.X..XX..XXXX.X..XXXXXX.XXXXX.XX..X.....X..XXX..XX..XXXX.XXXX.XXXXX.XX..XX\n\
.XXXXX..XXXXXXXX.X.XXX.....XX.X.XXX..X..XXX......XXXXX...X..X..XXXX.X.X...XXXX..X..X...X..XX.XX...XXXXXXX....XXXX..X..X.X...X.XX..X.XXXXX.XX.XX.XXXXX...XXX..X...X..X.XX..XXX.XXX....X.X.X.....X..........XX.X...X.XX.........\n\
XX.X....X..XX.XX.X..X..X..X..X.X.X.X.XX.X.X.XX.XXX....X.XX.XX..XX....XX.XXX.X.X..X.XX..X..XX.XX.....X..X.XX..XX.XXXXX..X.X..XX.XXX....XXX.XXXX.XX.XX.X.X.XX..XXX....X..X.XX.XX.X.XXXX...XX...XX........X.XX.X..X..X.XXX..XXXX.\n\
..XXXX...X.XX.X...X...X.X........X..X.XX..X.X.XX..XX.X.....XXX..X..............X.XX.X.X........XX.XX...X.X.X.....X..XXXXXXXX..XX.XX.XX.X.....X...XXX.X..XX..X.XX.X..X.XXXXX.X.X..X....XXX..X.XXXX..X...X..XXX..XXX..X.X.X....X\n\
X.....X..XX.X.....X..X..X...XXX.XXX.....X.XXX..X.X.XXXX...XX..X....XXXX..X..XXX.XX...X..X..XXXXXX.XXXX...X.X....X.XXX.XXXXX.X.XXX...XXXX.XX.X...X.XXXX.....XXX..X.XXX...XXX..XX..X...XX.XXX.....XX..XXXX.XXX.X..X...X..XXXXX..\n\
.XX..X.X....X.XXXXXX.X..XXX..XX....XXX..XX.X.X...XX.....X..X..X....XX...XXX.X.XXX...X..X..XXX..X...X.X....X...XX.X...X.XXXX.X.X.X.XX..XXX.X.XXX.....XX.XXXXX...XX..XXX.XX....X..X..X..X.X..X...XXX..XX.XXXXXXXX..XX..XX.....XX\n\
....XX.....XX.XX.X.XXX..X..X..X.XX......X...XXXX.XXX.X.X.X.XXX.X.XXXX....X...XX.XXXX..XXXXX...X...XX...XX..X.X.XX..X.XXXXXXX.X...X...XX.XXXX.X..X....X.XXXXX..XX.X...X.X..X.XXXX...X...X..X.X..XX.XXX....XX...X..X.X.XX.XXX.X.\n\
X.XX.X.X.X.X.X.X.XXXXXX.X...X.X.XX..X.XX..X..X.XXX..X.X.XX....X.X.X....XX.XX.XX..XXXXX..XX.X..XXXXX.X..X.X.X..X..XXXXX.X.XX..........XX.XXXXX.XX.X.XXX.XXX...XX..X.XX..XX..XXXXX.....X...X..X.X.XX.X.X...X.XX........XX.XX..XX\n\
X.XX.X...X...X.X...XXX.XXX.X....X...X.X.XX.XXXX..X..X.X.XXX.XXXX.X..XX..XX.X.XX.XXX...X...XXX.XXX..X...XX.XX.X.XXX..XXXXX..XX..X.....XXXX.XX.XXXX.X....XXXX.XXX.XXXXX.X.XXXX.XXXXXX...X.X...X..XXX...X...XX.X..X.....XXX....X.\n\
XXX.X....XX.X.XXX.....X..X.XXX.X.XX..XX..XX.XX.X...XX...XX.....XX.XX......XXXXX.XXXXX..X.XX.XXXX.X.X.XXX..XX.XX.X...X..XXX.XX.X.X......X.XX.X....X.XX..X.....XXX.X..X.XX...X...XXXX..XX.X..XX....XX.XX.X...X.X.X...XX..X.XXX.X\n\
XXX..X.X.X...XXX.X..XX....X.XX..X......XXX..XXXXX.X..XXX...XXX...X..XXX.X....X....X..X.XX.XXX.X...X...X...XX..........XX..X..X...XX.X..XXXX.XX.X.X...XX.XX....X...XXX..XX.X..X.XXX.X...XXX....XXXX......X..XX.XX.X..XXXX.XX.X.\n\
.X.X.XXX.X.X.X...XX.XX.X.XX.X.X....X..X.XX..X..XXXX.X.XX.....XX.XX...X....X....X..XXX.X.XX....XXX.X..XXXX..XXXX.X...XX.XXX.......X.X...X.XXXXX....X.XX..X..X.X...XX....X..XX..XXX.X..XXXX.X..X.XX.X...X.X.X.X..X..XX.X.X.XXX..\n\
XX.XX.X..X.X.X...X.X.X.XXX..XX..X.X..XXX..XXXXXXX.XXX...XX.XXX..XXXXXXXX..X......XXX.XXX.....X..X.XXX...XX.X...X...X.XXXXX..X....XX.XX.X....X.X..X.X....X...XXX...XXXXX...XX.X..XXX.XX..X...X.XX......X.XX.XXX..XXX..XXX..X.X.\n\
XXXXXX...X..XXXXXXX.XX...XX.XX.X...X.XX.XX.XXXX.XXX.X..X.XXXXXX..........X.X.XX....X....XX.XX.X.XX.XX...XXXXXX.....XX.X..XXX...X..XXX.X.XX.X.X.XXX...X..XX........XX..XX....XX.XXXX.X.....X.XXXXX.XX..X.X.XXXX.XX.XXX..XXXX..X\n\
XX...XXXXXXX..XXX.X.XXX.X...X.X.XXX.X..X.X..X.XX..XXX.XX.X.XXXX.XX.XXXXX.XX....X.XX..X.X..X.X.....XXX.XXXX.X......X..X...X....X..X....XXX..X..XX..X..XX..X.X.X..X.XX..X...X..XX.X.X.XXX.X.XX.XXX.X....X.X.X....XXX...X....XXX.\n\
.......XX.XX.XX..XXX.X.....X....XXX.XXX.X.XX.XX.X.X...XXX......XX.XX.XXX..XXX.X.X..XX..XX..X.X....XX.XXXXX..X...X.XXXXX.XX..XXX.XXXXXX.X.XX.XXXXX....XX.X.XXX.X..X..XX.X..XXX.X....X...XX.XXX.X...X.X..XX.X.X.XXXXX.X.X.XXXXXX\n\
");
}

void v5() {
printf("\
..XXXX.X..X.X.XX.XXX...XX.XX..XXXXXXX..XXX.X..XXXXXXX.XX..XXX.X.X.X..X..XXXX.XXX.XXXX...XXXXXXX.X.X.X...XX...XXX...XXXX..X.XX......X.X.X.X.X..XXXXX......X..X..XX....X.X.XX.XX.XX...X.XXX.X....X.....X.XX..X.X..XX.XXX...X....X..X..XX.X.XXXX.XX.XX.XXXX......XXX..X.XXXX....XX..XX.XX..........XX...XXXX....X.X........XXXXX..XXX....X.X...X.....X.X.X.XXXX..XX..X........X.XX.....X..XX...XX...XXXXX.XX.XX.X.X\n\
XX..XX.XXXXXX....XXXX.XXXXX....X.X...XX.......X...X.X.X.X...XXX..X.XXXX..X.XXX..XX.XXX.X...X.....XXX..XX.X.X..XXXX...XXX..X...X.......XXXX.X.X.XXXXXXXXX..X....X.X......XX.X.XX..X.X.X.XX..X..X.X...XX..XXXXXX.XXXX..XXX.X.XXXXXXX.X.X.XX.XX.XX.X.X.XX....X..X..XXXX......XXX.X..X....X....X.XX...X..X...XXXX..XX.XXX..XXXXX..XXX...XX...X.X..XX...XX.X..X..X..XXX.X.XX.XX..XXXXX.X.XXXXX.X...XX..X.XXX...XX.X.X\n\
X...X..XX..XXXXXX.X.XXXX...X.X.XXXXXXXX..XX.XXXX.X.XXX..XXX....X..X..XX......X...X.X.....XXX..X.XX...X......X..XX..XX.XXXX..X.XX.X.X.X..X.X........XXXXXXXXXXXX.X..XXXX.X.X.X..X.X.XXX...X.XXXXXXX.X..XXXX...X...X..XX..X.X.X.XX.XXX.XX.XX...X..X....XXXXX...XX.X..X..X...XXX..XX....X.X..XXXXX.XXX.X..X..XXXX.XXX..XXX.X.X.XXX...X....X.....X.X.XX......XX.XXX.....XX..X.X.XX.XX..X.XX...XXX.....X.XX..X...XXX.\n\
XXXXXX.XX..X.X.X.X.......X.XXXX.XXXXX.X..X.....XXX.X.XX.X..X.XXX.X.XX..X..XXX.X....XXXX..X...X..XX.XX.....XX.XXXX.X.XXX..X..XX.XXXX..XX.XX.....X.X.XXX.X.XX..XXX....XX..X.X...X.XXX..X.XXXX.XX..XXXXXX.XX..XXXX..XXXXX....X.XX..XXXXX.XXXX.XXX.....X.XX...XXX.X.X.XX..X....X.XX.XXX..X.X.....X....X.X....X..X......X.X..XX.XXXX.XXX..X.X.XX..XX.XX..XXX.XXX.X..XXXXX.X.XXX.X.X.X.X.X.X..XXX...XX..XXXX..XX....X.\n\
");
}
